### ISSUE TITLE
Error initializing firewall rules!

### ISSUE THREAD

**Issue by jdd272** [openNDS/openNDS#429] opened 2023-01-29 19:53 UTC
Hello,

I'm having an issue starting OpenNDS since my router has been upgraded to latest Snapshot r21950-90dbdb4941
It seems to be failing to create some of the iptables rules. The process is just dying without any error message, but I've spotted the following in the log : "Exiting because of error initializing firewall rules"

Hardware info :
```
"kernel": "5.10.165",
     "system": "MediaTek MT7621 ver:1 eco:3",
	"model": "Xiaomi Mi Router 3G",
	"board_name": "xiaomi,mi-router-3g",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "OpenWrt",
		"version": "SNAPSHOT",
		"revision": "r21950-90dbdb4941",
		"target": "ramips/mt7621",
		"description": "OpenWrt SNAPSHOT r21950-90dbdb4941"
	}
```

OpenNDS debug log : 
[opennds.log](https://github.com/openNDS/openNDS/files/10530748/opennds.log)

Packages version:
iptables-nft - 1.8.8-1
opennds - 9.10.0-1

I have a 2nd unit (same model) that I'm using as a dumb AP so no iptables. I grabbed it, upgraded it to the same snapshot version, and installed OpenNDS on it. So I'm 100% sure it has the right iptables-nft only. Didn't touch the default opennds config file except setting log level 3. It gives the same error message

Trying to run the iptables commands that are failing (giving return code 4 ) in the shell : 
```
iptables --wait -t filter -I FORWARD 1 -m mark --mark 0x10000/0x
30000 -j REJECT
iptables v1.8.8 (nf_tables):  CHAIN_ADD failed (File exists): chain FORWARD
```

```
iptables --wait -t filter -I INPUT -i br-guest -s 0.0.0.0/0 -j n
dsRTR
iptables v1.8.8 (nf_tables):  CHAIN_ADD failed (File exists): chain INPUT
```

```
iptables --wait -t filter -I FORWARD -i br-guest -s 0.0.0.0/0 -
j ndsNET
iptables v1.8.8 (nf_tables):  CHAIN_ADD failed (File exists): chain FORWARD
```

I've also noticed this warning in the logs, but not sure if this is related:
```Sun Jan 29 20:10:47 2023 daemon.info opennds[22593]: Kernel does not support iptables mark masking. Using empty mask.```

Any help would be much appreciated ! thank you

**Comment by bluewavenet** [comment] 2023-01-29 20:47
@jdd272 
I formatted your post. Please make sure to **use the <> tool at the top of the text box** when adding code or log outputs.

Why are you using OpenWrt snapshot?
Snapshot is not a stable release.

From the OpenWrt downloads page:

> Development snapshots are automatic unattended daily builds of the current OpenWrt development master branch. Bear in mind that these images are generally not tested, use them at your own risk. 

Although openNDS v9.10.0 was tested on a snapshot, **there is no guarantee to will work on today's snapshot**, something may have broken.

> Didn't touch the default opennds config file except setting log level 3

There seem to be many non-default entries in the config file.

Have you tested using just the default config file? (a copy of it is stored as `/etc/opennds/config.uci`)

Please show the output of:
`uci export opennds`

Also show the output of:
`nft list ruleset`

**Comment by jdd272** [comment] 2023-01-29 21:55
Apologies, I realized about the format after I've submitted the issue.

> Why are you using OpenWrt snapshot?
Snapshot is not a stable release.

I'm using Snapshot because at some point in time I couldn't use some other features while being on the stable branch. Also I'm an enthusiast and I fully understand that things may break, it's just my home router so it isn't critical to me if my guest network stops working.

> There seem to be many non-default entries in the config file.

This is because the log is from my main unit (the one that had OpenNDS already installed). I had the same result on the 2nd AP though.

From the 2nd AP, fresh OpenNDS install and default config file + debuglevel 3 : 
```
diff /etc/config/opennds /etc/opennds/config.uci 
17c17
< 	option debuglevel '3'
---
> 	#option debuglevel '2'
```

 `nft list ruleset`
```
table ip filter {
	chain INPUT {
		type filter hook input priority -100; policy accept;
	}

	chain FORWARD {
		type filter hook forward priority -100; policy accept;
	}
}
table ip mangle {
	chain PREROUTING {
		type filter hook prerouting priority mangle; policy accept;
	}

	chain POSTROUTING {
		type filter hook postrouting priority mangle; policy accept;
	}
}
table ip nat {
	chain PREROUTING {
		type nat hook prerouting priority dstnat; policy accept;
	}
}
table inet fw4 {
	chain input {
		type filter hook input priority filter; policy accept;
		iifname "lo" accept comment "!fw4: Accept traffic from loopback"
		ct state established,related accept comment "!fw4: Allow inbound established and related flows"
		tcp flags syn / fin,syn,rst,ack jump syn_flood comment "!fw4: Rate limit TCP syn packets"
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		ct state established,related accept comment "!fw4: Allow forwarded established and related flows"
		jump handle_reject
	}

	chain output {
		type filter hook output priority filter; policy accept;
		oifname "lo" accept comment "!fw4: Accept traffic towards loopback"
		ct state established,related accept comment "!fw4: Allow outbound established and related flows"
	}

	chain prerouting {
		type filter hook prerouting priority filter; policy accept;
	}

	chain handle_reject {
		meta l4proto tcp reject with tcp reset comment "!fw4: Reject TCP traffic"
		reject comment "!fw4: Reject any other traffic"
	}

	chain syn_flood {
		limit rate 25/second burst 50 packets return comment "!fw4: Accept SYN packets below rate-limit"
		drop comment "!fw4: Drop excess packets"
	}

	chain dstnat {
		type nat hook prerouting priority dstnat; policy accept;
	}

	chain srcnat {
		type nat hook postrouting priority srcnat; policy accept;
	}

	chain raw_prerouting {
		type filter hook prerouting priority raw; policy accept;
	}

	chain raw_output {
		type filter hook output priority raw; policy accept;
	}

	chain mangle_prerouting {
		type filter hook prerouting priority mangle; policy accept;
	}

	chain mangle_postrouting {
		type filter hook postrouting priority mangle; policy accept;
	}

	chain mangle_input {
		type filter hook input priority mangle; policy accept;
	}

	chain mangle_output {
		type route hook output priority mangle; policy accept;
	}

	chain mangle_forward {
		type filter hook forward priority mangle; policy accept;
	}
}
```

` uci export opennds`

```
package opennds

config opennds
	option enabled '1'
	option debuglevel '3'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 443'
```

New log file : 
[opennds.log](https://github.com/openNDS/openNDS/files/10530942/opennds.log)

Here are the 3 commands that are failing:
```
cat /tmp/opennds.log | grep -B1 "21750.*code \[ 4"
Sun Jan 29 22:40:25 2023 daemon.debug opennds[21750]: Executing command: iptables --wait -t filter -I FORWARD 1 -m mark --mark 0x10000/0x30000 -j REJECT > /dev/null 2>&1
Sun Jan 29 22:40:26 2023 daemon.debug opennds[21750]: iptables command [ -t filter -I FORWARD 1 -m mark --mark 0x10000/0x30000 -j REJECT ], return code [ 4 ]
--
Sun Jan 29 22:40:31 2023 daemon.debug opennds[21750]: Executing command: iptables --wait -t filter -I INPUT -i br-lan -s 0.0.0.0/0 -j ndsRTR
Sun Jan 29 22:40:32 2023 daemon.debug opennds[21750]: iptables command [ -t filter -I INPUT -i br-lan -s 0.0.0.0/0 -j ndsRTR ], return code [ 4 ]
--
Sun Jan 29 22:40:36 2023 daemon.debug opennds[21750]: Executing command: iptables --wait -t filter -I FORWARD -i br-lan -s 0.0.0.0/0 -j ndsNET
Sun Jan 29 22:40:37 2023 daemon.debug opennds[21750]: iptables command [ -t filter -I FORWARD -i br-lan -s 0.0.0.0/0 -j ndsNET ], return code [ 4 ]
```

**Comment by bluewavenet** [comment] 2023-01-30 07:34
@jdd272 
It would be useful if you could try on OpenWrt 22.03.3 rather than snapshot at least for test purposes.
I note the current snapshot has iptables v1.8.8, whereas 22.03.3 has v1.8.7. Perhaps the problem lies there.

Later today I might have time to test on the current snapshot to see if I can replicate the issue.

**Comment by bluewavenet** [comment] 2023-01-30 15:57
@jdd272 
I can confirm that the issue is due to compatibility with iptables-nft v1.8.8 that is present in the current OpenWrt snapshot.

I would suggest you only use OpenWrt 22.03.x which comes with iptables-nft v1.8.7 and does not have the issue.

However if you really need snapshot, I have a patch you can apply that fixes the problem with this version of iptables-nft.

**Comment by jdd272** [comment] 2023-01-30 16:29
Great ! It would be awesome if you can share the patch, I'm also curious to see how to resolve it ... I'm not too god with nftables ^^
P.S: I will switch over to stable when I stop being too lazy to redo all my configs

**Comment by bluewavenet** [comment] 2023-01-30 20:40
@jdd272 
I've merged the patched library into openNDS master.
You can download from Github:

```
cd /usr/lib/opennds
mv libopennds.sh libopennds.sh.old
wget https://raw.githubusercontent.com/openNDS/openNDS/master/forward_authentication_service/libs/libopennds.sh
chmod 744 test/libopennds.sh
```

**Comment by jdd272** [comment] 2023-01-30 20:57
Thanks a lot, I've just tried it and can confirm it is working now

**Comment by bluewavenet** [comment] 2023-02-13 10:22
@jdd272 
Closing for now....
This issue will be fixed properly in the next release with the phase 2 migration to nftables.

**Closed by bluewavenet** 2023-02-13 10:22 UTC

**Comment by lauravizcaino** [comment] 2023-04-25 20:08
Hi, 

I´m having the same error, I have Snapshot since is the only image for TP-Link EAP225 V3. 
Packages version:
iptables-nft - 1.8.8-1
opennds - 9.10.0-1

I was having the problem of: 
`"Exiting because of error initializing firewall rules"`

I tried with the above mentioned patch, but now I have the following error:
`daemon.err opennds: Failed to create Walled Garden`

@bluewavenet Your help would be much appreciated, thanks

**Comment by bluewavenet** [comment] 2023-04-30 09:54
@lauravizcaino 

>  iptables-nft - 1.8.8-1

OpenWrt master had iptables-nft updated which broke OpenNDS for snapshot versions.

This is fixed in v10.0.0, where full migration to nftables is complete.
Release of 10.0.0 should be expected within the next week.

**Comment by 1ucay** [comment] 2023-06-16 20:07
Hello, when will be avaliable version 10? Thank you.

**Comment by bluewavenet** [comment] 2023-06-17 05:54
@1ucay 
v10.0.0 was not released, instead development was fast-tracked to version 10.1.0 not only incorporating full migration to nftables, but also supporting ipsets/nftsets and native uci configuration for all Linux flavours.
Expect v10.1.0 "soon" ;-)

**Comment by 1ucay** [comment] 2023-06-17 16:38
Ok thank you, I have to simply wait :)

**Comment by rafaelfelix** [comment] 2023-12-31 13:40
I've just faced the same issue using OpenWRT 23.05.2 and OpenNDS v10.2.0 running on a Linksys EA4500 v2.

Logs: [opennds.log](https://github.com/openNDS/openNDS/files/13801268/opennds.log)

Additional info:

```bash
root@OpenWrt:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='23.05.2'
DISTRIB_REVISION='r23630-842932a63d'
DISTRIB_TARGET='kirkwood/generic'
DISTRIB_ARCH='arm_xscale'
DISTRIB_DESCRIPTION='OpenWrt 23.05.2 r23630-842932a63d'
DISTRIB_TAINTS=''
```

The log lines that caught my attention were:

```
Sun Dec 31 13:21:13 2023 daemon.debug opennds[24586]: Executing command: nft add rule ip nds_nat ndsOUT ip daddr status.client tcp dport 2050 counter accept
Sun Dec 31 13:21:13 2023 daemon.debug opennds[24586]: nftables command [ add rule ip nds_nat ndsOUT ip daddr status.client tcp dport 2050 counter accept ], iteration [ 0 ]return code [ 1 ]
...
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: restart command [ /usr/lib/opennds/dnsconfig.sh "restart_only" & ]
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: SIGCHLD handler: Process PID 27138 exited normally, status 0
Sun Dec 31 13:21:14 2023 daemon.info opennds[24586]: Dnsmasq restarted
Sun Dec 31 13:21:14 2023 daemon.err opennds[24586]: Error initializing firewall rules! Cleaning up
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: Destroying our nftables entries
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: Executing command: /usr/lib/opennds/libopennds.sh "delete_chains"
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: Reading command output
Sun Dec 31 13:21:14 2023 daemon.debug opennds[24586]: command output: []
Sun Dec 31 13:21:14 2023 daemon.info opennds[24586]: Chain delete request sent
Sun Dec 31 13:21:14 2023 daemon.err opennds[24586]: Exiting because of error initializing firewall rules
```

**Comment by bluewavenet** [comment] 2023-12-31 13:55
@rafaelfelix 
Please open a new issue for this as it is different to that here and the solution is known.
