### ISSUE TITLE
NDS cannot reach HTTPS FAS

### ISSUE THREAD

**Issue by datablitz7** [openNDS/openNDS#527] opened 2023-09-28 19:54 UTC
I have a setup with OpenNDS on Linux and a FAS on the same network, using the fas php files.

Using fas_secure_enabled 2 and  faspath '/fas-aes.php everything works as expected.
Using fas_secure_enabled 3 and  faspath '/fas-aes-https.php results in a timeout page:

![mstsc_NUbVQUCwVO](https://github.com/openNDS/openNDS/assets/2716562/2cdf4b0e-0b83-4974-b7cc-8caac9b0be8d)

My OpenNDS config looks like this:
```
config opennds
    option log_mountpoint '/logs'
    option dhcp_default_url_enable '0'
    option gatewayname 'HOTSPOT'
    option enable_serial_number_suffix '0'
    option gatewayfqdn 'connect.hotspot.example.com'
    option fasremotefqdn 'auth.hotspot.example.com'
    option faspath '/fas-aes-https.php'
    option fas_secure_enabled '3'
    option faskey 'somerandomkey'
    option fasremoteip '10.100.100.201'
    option fasport '443'
    option gatewayinterface 'eth1'
    option ndsctlsocket /tmp/sockets/ndsctl.sock
    option login_option_enabled ‘3’
    option themespec_path /usr/lib/opennds/theme_user_email_login.sh
```

OpenNDS Logs are showing this:
```
PHP Warning:  fopen(https://auth.hotspot.example.com:443/fas-aes-https.php): Failed to open stream: Connection timed out in /usr/lib/opennds/post-request.php on line 38
```

Network tracing on OpenNDS:
```
IP OpenNDS.33126 > FAS.443: Flags [S], seq 2306981304, win 64240, options [mss 1460,sackOK,TS val 3346637301 ecr 0,nop,wscale 7], length 0
IP FAS.443 > OpenNDS.33126: Flags [S.], seq 1299055292, ack 2306981305, win 65160, options [mss 1460,sackOK,TS val 4033708768 ecr 3346636270,nop,wscale 7], length 0
IP OpenNDS > FAS: ICMP NDS tcp port 33126 unreachable, length 68
```

Network tracing on FAS:
```
IP OpenNDS.57798 > FAS.443: Flags [S], seq 659352749, win 64240, options [mss 1460,sackOK,TS val 3347265141 ecr 0,nop,wscale 7], length 0
IP FAS.443 > OpenNDS.57798: Flags [S.], seq 198222843, ack 659352750, win 65160, options [mss 1460,sackOK,TS val 4034336608 ecr 3347262094,nop,wscale 7], length 0
IP OpenNDS > FAS: ICMP NDS tcp port 57798 unreachable, length 68
```

If I flush the nds_filter table, (`nft flush table nds_filter`) authentication works. Shouldn't this work out of the box?
 What am I missing? Any ideas?

**Comment by bluewavenet** [comment] 2023-09-29 07:29
@datablitz7 

> What am I missing? 

Well the main problem here is that level 3 is intended for use with an Internet hosted web server with valid TLS certificates.

A hint can be seen here:
`PHP Warning:  fopen(https://auth.hotspot.example.com:443/fas-aes-https.php): Failed to open stream: `

This is almost certainly because your FAS web server is on the local private network so will have invalid TLS certificates.

Also the domain `example.com` is a valid Internet domain so should not really be used here, although this is most likely not the cause of your problem.
Presumably you have added `connect.hotspot.example.com` and `auth.hotspot.example.com` to your local dns server.

The default value for gatewayfqdn is `status.client`

The value for fasremotefqdn would be set to the external fqdn of a remote FAS web server with a valid public ip address.

**Comment by datablitz7** [comment] 2023-09-29 08:22
Thanks for the response.

The domain has been masked with example.com for the purposes of this ticket. The FAS has a valid TLS certificate, and the FQDNs are accessible over local DNS. 

These pieces are already in place and working as expected. The only thing missing is something in the default firewall rules is apparently blocking the NDS to communicate with the FAS, evidenced by the fact that when flushing the nds_filter chain, everything works. As per my original message:

> If I flush the nds_filter table, (nft flush table nds_filter) authentication works. Shouldn't this work out of the box?

Your help would be greatly appreciated.

**Comment by bluewavenet** [comment] 2023-09-29 10:02
@datablitz7 
` option fasremoteip '10.100.100.201'`

This is a private ip address, so the fas web server is not Internet hosted. In addition the certificate will be invalid for a private ip.

**_Your config with a local fas does not meet the requirements of level 3._**

For level 3, openNDS effectively sets up an inbound nat traversal tunnel from the fas web server to openNDS. This allows the external fas web server to send data to openNDS. But in your configuration, apart from certificate errors, a local fas will be blocked from communicating through the tunnel to openNDS by openNDS's own nftables settings.
For a local fas, you must use levels 1 or 2, eg fas-aes.php or fas-hid.php.

**Closed by bluewavenet** 2023-09-29 10:02 UTC

**Comment by datablitz7** [comment] 2023-09-29 11:04
Understood, although the documentation does not explicitly explain the FAS being public/non local, as a requirement for level 3. 

Can you explain how this is achieved/enforced, as I cannot see a particular rule that drops/rejects any traffic anywhere in the built in rules?

It should stand to reason that some explicit firewall rules should allow this use case.

**Comment by bluewavenet** [comment] 2023-09-29 13:57
@datablitz7 

>  documentation does not explicitly explain the FAS being public/non local, as a requirement for level 3.

Good point. Yes, documentation can always benefit from a bit more work. It does say though that it should be Internet hosted:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-https-php

> Can you explain how this is achieved/enforced, as I cannot see a particular rule that drops/rejects any traffic anywhere in the built in rules?

Yes. The openNDS ruleset allows inbound traffic to the router to a default or specified list of ports eg for a client to access a web server running on the router. All other inbound traffic is rejected.
But if the router accesses a web server on the local network, response packets are rejected as they will be on a random high port.

This is intentional, and there is no config to allow random inbound high ports.

It could be argued that this could be added as an enhancement, but until now, a requirement has not been identified (particularly as level 3 is intended to be using an Internet hosted server).

You could insert a rule to allow this from a specified ip address, but you would have to do this **_after_** openNDS is running.

Try this:

`nft insert rule ip nds_filter ndsRTR index 2 ip saddr 10.100.100.201 counter accept`

You could write a script to check if opennds is up, then run the command to insert the rule.

Code to test if opennds is up:
`ndsup=$(/usr/lib/opennds/libopennds.sh check_heartbeat &>null; echo $?)`

If $ndsup is 0, it is up.

**Comment by datablitz7** [comment] 2023-09-29 18:05
@bluewavenet That works but I think I have a nice way to achieve this. I cannot see a contribution guideline. Would you be open to a PR to add this "enhancement"?

**Comment by bluewavenet** [comment] 2023-09-29 19:40
PRs are always welcome.

I have also looked at the code and just a few small mods to existing should do it.

I would like to see your version though!
