### ISSUE TITLE
Setting Up a Remote FAS?

### ISSUE THREAD

**Issue by bharathkspot** [openNDS/openNDS#141] opened 2021-04-07 12:24 UTC
as i am understood the concepts for FAS settings for OpenNS from https://opennds.readthedocs.io/ tried with some configs to get the clarity on the NDS things, and accessing internet via NDS to the connected desktop from the Router where in which openNDS is running.

below are the sample configs i have tried.

uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='onboard-wifi.net'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].faspath='/fas/fas.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='1'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

am able to get the hotspot login page once after running the openNDS in router and connecting the LAN to Desktop as expected from the docs. below is the snapshot

![Screenshot from 2021-04-07 17-40-06](https://user-images.githubusercontent.com/81303982/113865739-14051f00-97ca-11eb-94b0-63d20dc2b4ec.png)

but further am not able to access the internet, it will be really helpful if anyone provides some inputs or suggestions w.r.t settings if we missing out  anything.

thanks in advance

**Comment by bluewavenet** [comment] 2021-04-07 13:03
@bharathkspot 
As mentioned in #130 the two UCI config lines:
```
opennds.@openNDS[0].fasremotefqdn='onboard-wifi.net'
opennds.@openNDS[0].fasremoteip='46.32.240.41'
```
These are not defaults, but included only as examples of the format of the options in the config file.
The web site is however a real one, so this indicates that openNDS is running and redirecting you to `http://onboard-wifi.net/`
This web site does not have a FAS set up on it.

First, a fundamental question: Do you have administrative access to an Internet hosted web site with php support?
This is essential for running a remote Internet based FAS. (It is possible to use something other than PHP but we will not go into that here)

**Comment by got24batman** [comment] 2021-04-08 05:44
Just wanted to have a Glimpse of how OpenNDS works with external FAS.
I referred to the following link **https://opennds.readthedocs.io/en/stable/fas.html** to configure openNDS
Following is my openNDS configuration
root@OpenAp-40026c:/# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].webroot='/etc/opennds/htdocs'
opennds.@opennds[0].statuspage='status.html'
opennds.@opennds[0].splashpage='splash_sitewide.html'
opennds.@opennds[0].binauth='/usr/lib/opennds/binauth_sitewide.sh'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='4096'
opennds.@opennds[0].downloadquota='4096'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='blue-wave.net'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].faspath='/nds/fas-hid.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='1'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

I am able to redirect the 3-rd party client to splash page. But the 3rd party client is not getting internet post authenticating.
Can you please help, what exactly I am missing ??
![Screenshot from 2021-04-08 10-58-36](https://user-images.githubusercontent.com/77356294/113974439-8eca4a80-985b-11eb-9c54-de647fdaae86.png)
![Screenshot from 2021-04-08 10-58-48](https://user-images.githubusercontent.com/77356294/113974441-8ffb7780-985b-11eb-9bb1-7ddc76df556c.png)
![Screenshot from 2021-04-08 10-58-52](https://user-images.githubusercontent.com/77356294/113974442-90940e00-985b-11eb-9634-90d3d0b3bbd3.png)

**Comment by bharathkspot** [comment] 2021-04-08 06:56
> @bharathkspot
> As mentioned in #130 the two UCI config lines:
> 
> ```
> opennds.@openNDS[0].fasremotefqdn='onboard-wifi.net'
> opennds.@openNDS[0].fasremoteip='46.32.240.41'
> ```
> 
> These are not defaults, but included only as examples of the format of the options in the config file.
> The web site is however a real one, so this indicates that openNDS is running and redirecting you to `http://onboard-wifi.net/`
> This web site does not have a FAS set up on it.
> 
> First, a fundamental question: Do you have administrative access to an Internet hosted web site with php support?
> This is essential for running a remote Internet based FAS. (It is possible to use something other than PHP but we will not go into that here)


as of now i dont have such setup with php support, is it ok to set it up it on the same desktop which i am using for testing openNDS captive portal thing?

**Comment by bluewavenet** [comment] 2021-04-08 07:21
@bharathkspot 
Do you mean set up an http/php server on your desktop? Yes, this will work for the fas-hid.php and fas-aes.php examples (but **not** fas-aes-https.php).
This "test" web server on your desktop will not of course be shared hosting so the openNDS config will be a little simpler, not needing fasremotefqdn

**Comment by bharathkspot** [comment] 2021-04-08 07:25
yeah, since u told that we need an internet hosted website with php support to run remote internet FAS, so i thought of using my desktop as website with php support.

am trying to use some android apps too for website support,

**Comment by bluewavenet** [comment] 2021-04-08 07:36
@got24batman 
You have these config settings:
```
opennds.@openNDS[0].fasport='80'
opennds.@openNDS[0].fasremotefqdn='blue-wave.net'
opennds.@openNDS[0].fasremoteip='46.32.240.41'
opennds.@openNDS[0].faspath='/nds/fas-hid.php'
```
Note the documentation at https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-hid-php
This does say to change to the values for **YOUR** actual server.
As you can see, the file `http://blue-wave.net/nds/fas-hid.php`  does exist but there is no guarantee what version it is or if it matches the version of openNDS you are using. It was used at some time for testing purposes.....

What version of openNDS do you have? ( the command `ndsctl status` will tell you)

**Comment by bluewavenet** [comment] 2021-04-08 07:38
@bharathkspot 

> i thought of using my desktop as website with php support.

Yes, this will work well for testing.

**Comment by got24batman** [comment] 2021-04-08 08:02
@bluewavenet
I am using opennds 5.1

By using the link : https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-hid-php
was trying to configure opennds to use **fas-aes-https.php**   
uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].webroot='/etc/opennds/htdocs'
opennds.@opennds[0].statuspage='status.html'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='4096'
opennds.@opennds[0].downloadquota='4096'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].fasremotefqdn='blue-wave.net'
opennds.@opennds[0].fasremoteip='46.32.240.41'
`opennds.@opennds[0].faspath='/nds/fas-aes-https.php'`
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].authenticated_users='allow all'
`opennds.@opennds[0].users_to_router='allow` tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'
I am unable to re-direct 3rd part sta to splash page hosted by blue-wave, instead I am able to browse internet ??
could you please help

**Comment by bluewavenet** [comment] 2021-04-08 08:20
@got24batman 
The current version of openNDS is v8.1.1
I guess you are on OpenWrt 19.07.x

I would strongly suggest that before you do anything else you upgrade both openNDS and libmicrohttpd to the versions found in OpenWrt Snapshot packages.
These are stable versions despite being in snapshot.
Once you have upgraded I can give you help getting it running. Note the new versions have not been backported to OpenWrt 19.07.x packages as backporting is restricted normally to bug fixes only. Unfortunately openNDS 5.1 is very outdated now, particularly if you need https FAS support.

Let me know the hardware you are using if you need help upgrading.

Note also my comment:

> As you can see, the file `http://blue-wave.net/nds/fas-hid.php` does exist but there is no guarantee what version it is or if it matches the version of openNDS you are using. It was used at some time for testing purposes.....

**Comment by got24batman** [comment] 2021-04-08 09:41
Have updated the opennds and libmicrohttpd, still facing the same issue.
opkg list | grep opennds
opennds - 8.1.1-1

opkg list | grep libmicro
libmicrohttpd-no-ssl - 0.9.71-1

**Comment by bluewavenet** [comment] 2021-04-08 10:02
@got24batman 
Yes you will have the same issue. Now you need to upload fas-aes-https **to your own server** and point openNDS to it.

For testing purposes I can upload the correct version to blue-wave.net if it would be helpful.
I will do this now and post here when done.

**Comment by bluewavenet** [comment] 2021-04-08 10:17
@got24batman 
All in place and ready to go.
**But first you need to modify your config with these options (note the faspath is different).**

```
	option use_outdated_mhd '0'
	option fasremotefqdn 'blue-wave.net'
	option fasremoteip '46.32.240.41'
	option fasport '443'
	option faspath '/fas/fas-aes-https.php'
	option fas_secure_enabled '3'
	option faskey '1234567890'

```
You will then need to restart openNDS for this to take effect:
`service opennds restart`

**Comment by got24batman** [comment] 2021-04-08 10:44
@bluewavenet 
Thanks for the quick response.
 I am able to get the splash page, using the above configuration. But still, the 3rd party station is not getting internet.
Can you please share the /fas/fas-aes-https.php file ??

**Comment by bluewavenet** [comment] 2021-04-08 10:52
@got24batman 

> But still, the 3rd party station is not getting internet.

What do you mean by this?

After installing 8.1.1, you will find fas-aes-https.php in /etc/opennds

**Comment by bluewavenet** [comment] 2021-04-08 11:04
@got24batman 
Are you working with, or are you the same person as @bharathkspot ?
Here are the FAS server logs:
```
2021-04-08 10:12:31, fas-aes-https, %24BlueWave%20Captive%20Portal, Test%20Client, test.client@blue-wave.net, 10.27.5.115, 74:de:2b:b1:70:33, wlan0, Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0, http://onboard-wifi.net/
2021-04-08 10:39:25, fas-aes-https, OpenWrt%20openNDS, bharath, bhara@gmail, 192.168.1.174, 74:78:27:03:03:b7, br-lan, Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36, http://detectportal.firefox.com/success.txt
2021-04-08 10:40:06, fas-aes-https, OpenWrt%20openNDS, bharath, bhara@gmail, 192.168.1.174, 74:78:27:03:03:b7, br-lan, Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36, http://detectportal.firefox.com/success.txt
```
I would guess from this that you are logging in from the Error 511 page.....

**Comment by got24batman** [comment] 2021-04-08 11:07
Actually, I am working with  @bharathkspot.

**Comment by bluewavenet** [comment] 2021-04-08 11:08
@got24batman 
There is no hiding from me ;-)

**Comment by bharathkspot** [comment] 2021-04-08 11:16
> @got24batman
> Are you working with, or are you the same person as @bharathkspot ?
> Here are the FAS server logs:
> 
> ```
> 2021-04-08 10:12:31, fas-aes-https, %24BlueWave%20Captive%20Portal, Test%20Client, test.client@blue-wave.net, 10.27.5.115, 74:de:2b:b1:70:33, wlan0, Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0, http://onboard-wifi.net/
> 2021-04-08 10:39:25, fas-aes-https, OpenWrt%20openNDS, bharath, bhara@gmail, 192.168.1.174, 74:78:27:03:03:b7, br-lan, Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36, http://detectportal.firefox.com/success.txt
> 2021-04-08 10:40:06, fas-aes-https, OpenWrt%20openNDS, bharath, bhara@gmail, 192.168.1.174, 74:78:27:03:03:b7, br-lan, Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36, http://detectportal.firefox.com/success.txt
> ```
> 
> I would guess from this that you are logging in from the Error 511 page.....

we are two, not the same, since @got24batman was not having the hardware for timebeing to reply u quickly me did the testing with those configs,  sincere apologies for the misunderstandings @bluewavenet .

**Comment by bluewavenet** [comment] 2021-04-08 11:37
@got24batman @bharathkspot 
No misunderstandings - I just thought it was funny :-D

What do you mean by "3rd party station"?

From the logs it appears you logged in successfully.

**Comment by bluewavenet** [comment] 2021-04-08 11:41
@got24batman @bharathkspot 
This time your desktop CPD:
`2021-04-08 11:22:15, fas-aes-https, OpenWrt%20openNDS, bharat, bha@gmail.com, 192.168.1.174, 74:78:27:03:03:b7, br-lan, Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15, http://nmcheck.gnome.org/`

**Comment by bharathkspot** [comment] 2021-04-08 11:47
> @got24batman @bharathkspot
> This time your desktop CPD:
> `2021-04-08 11:22:15, fas-aes-https, OpenWrt%20openNDS, bharat, bha@gmail.com, 192.168.1.174, 74:78:27:03:03:b7, br-lan, Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15, http://nmcheck.gnome.org/`

yeah, last time the desktop which am using for testing was connected with other wifi, and openNDS router's LAN cable, so the CPD will trigger only if i turn off the wifi and connect the LAN cable after restarting the openNDS

**Comment by bluewavenet** [comment] 2021-04-08 11:50
@bharathkspot 
What do you mean by "3rd party station"?

**Comment by bharathkspot** [comment] 2021-04-08 11:55
> @bharathkspot
> What do you mean by "3rd party station"?

the '3rd party station' means the desktop which is connected to router where openNDS is running. even after getting the below page, am not able to access the internet, is there any firewall setting also to be done?
![Screenshot from 2021-04-08 16-52-29](https://user-images.githubusercontent.com/81303982/114022421-5fcdcc00-988f-11eb-9cf4-9fc1a4bf8bb4.png)
![Screenshot from 2021-04-08 16-52-18](https://user-images.githubusercontent.com/81303982/114022428-60fef900-988f-11eb-9afe-4c8b1d9a8d63.png)
![Screenshot from 2021-04-08 16-52-14](https://user-images.githubusercontent.com/81303982/114022430-61978f80-988f-11eb-8ef4-5b59b461c0b6.png)

**Comment by bluewavenet** [comment] 2021-04-08 12:11
@bharathkspot 
It is working here **_on the same remote FAS_**.

Your first image is the final landing page served by the FAS. It will only serve this page when openNDS has informed it that the client has been allowed access to the Internet. You will probably find most Android and Apple devices will just flash up this page before immediately closing it (this is by design in the CPD standard - but not mandatory.) 

Have you tried opening your browser and going to some web site? Your image looks like the desktop CPD popup.. difficult to tell. That popup is a very restricted browser and cannot be used for normal Internet access.

What does status.client show?
What is the output of `ndsctl status` ?

**Comment by bharathkspot** [comment] 2021-04-08 12:36
@bluewavenet,

fyi: currenlty we are not testing with androi/apple devices, using laptop only via LAN cable

yes i have tried openning website google.com through website also and tried ping 8.8.8.8 also not working,

below is the output of 'ndsctl status'

_root@OpenAp-400270:~# ndsctl status
==================
openNDS Status
====
Version: 8.1.1
Uptime: 1m 18s
Gateway Name: OpenWrt openNDS
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.1.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 3, URL: https://blue-wave.net:443/fas/fas-aes-https.php
Client Check Interval: 60s
Rate Check Window: 2 check intervals (120s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 296 kByte; avg: 30.43 kbit/s
Total upload: 98 kByte; avg: 10.12 kbit/s
====
Client authentications since start: 0
Current clients: 1

Client 0
  IP: 192.168.1.174 MAC: 74:78:27:03:03:b7
  Last Activity: Thu Apr 08 12:30:29 2021 (57s ago)
  Session Start: -
  Session End:   -
  Token: 58a5353a
  State: Preauthenticated
  Upload rate limit: not set
  Download rate limit: not set
  Upload quota: not set
  Download quota: not set
  Upload this session: 0 kB; Session avg: 0.00 kb/s
  Download this session: 0 kB; Session avg: 0.00 kb/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========
root@OpenAp-400270:~#_

**Comment by bluewavenet** [comment] 2021-04-08 12:51
@bharathkspot 
If you stop opennds, do you then have Internet access?
ie:
`service opennds stop`

**It is not necessary to make any firewall changes.** In fact if you do you will most likely break something unless you know exactly what you are doing for some special purpose.

For comparison, here is the output of ndsctl status on my test system here:

```
==================
openNDS Status
====
Version: 8.1.1
Uptime: 2h 35m 12s
Gateway Name: $BlueWave Captive Portal
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://10.27.1.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 3, URL: https://blue-wave.net:443/fas/fas-aes-https.php
Client Check Interval: 600s
Rate Check Window: 2 check intervals (1200s)
Preauthenticated Client Idle Timeout: 30m
Authenticated Client Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): no limit
Upload quota (default per client): no limit
Total download: 56676 kByte; avg: 48.69 kbit/s
Total upload: 5712 kByte; avg: 4.91 kbit/s
====
Client authentications since start: 1
Current clients: 1

Client 0
  IP: 10.27.5.115 MAC: 74:de:2b:b1:70:33
  Last Activity: Thu Apr 08 12:46:47 2021 (0s ago)
  Session Start: Thu Apr 08 10:12:37 2021 (2h 34m 10s ago)
  Session End:   -
  Token: 5e7d843a
  State: Authenticated
  Upload rate limit: not set
  Download rate limit: not set
  Upload quota: not set
  Download quota: not set
  Upload this session: 5574 kB; Session avg: 4.82 kb/s
  Download this session: 56020 kB; Session avg: 48.45 kb/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
Walled Garden FQDNs: none
Walled Garden Ports: none
========

```

**Comment by bluewavenet** [comment] 2021-04-08 12:58
@bharathkspot 
Ah! By any chance, is your OpenWrt/openNDS test router connected to your ISP's router, and does the ISP's router also have the IP subnet 192.168.1.0?
If so this might be the issue.
Make sure your test router's lan is NOT the same subnet as your ISP's router lan.

**Comment by bharathkspot** [comment] 2021-04-09 05:29
> @bharathkspot
> Ah! By any chance, is your OpenWrt/openNDS test router connected to your ISP's router, and does the ISP's router also have the IP subnet 192.168.1.0?
> If so this might be the issue.
> Make sure your test router's lan is NOT the same subnet as your ISP's router lan.


yeah for that i hav already tested with 172.168.5.1 subnet also, but same behaviour.

**Comment by bluewavenet** [comment] 2021-04-09 06:50
@bharathkspot
As I asked before:
If you stop opennds, do you then have Internet access?
ie do:
`service opennds stop`
Then try connecting.

**Comment by bharathkspot** [comment] 2021-04-09 07:04
no i dont have internet access, if stop openNDS also, since i ll be turing of my laptop's wifi

these are steps i ll follow for testing openNS:
1. run openNDS on router (service opennds start)
2. before connecting to the router where in which openNDS is running i ll always turnoff wi-fi on my laptop
3. and connect LAN cable from openNDS router to laptop, then the CPD will trigger on my laptop, 
4. i ll do authentication and  try to access internet

in my case internet is not able to access in laptop vai openNDS.

**Comment by bluewavenet** [comment] 2021-04-09 07:14
@bharathkspot 
1. service opennds stop
2. turn off wi-fi on laptop
3. connect LAN cable from openNDS router to laptop
4. Does laptop have Internet access?

**What is the answer to step 4?**

**Comment by bharathkspot** [comment] 2021-04-09 07:20
> @bharathkspot
> 
> 1. service opennds stop
> 2. turn off wi-fi on laptop
> 3. connect LAN cable from openNDS router to laptop
> 4. Does laptop have Internet access?
> 
> **What is the answer to step 4?**

@bluewavenet 
'No laptop does not hav internet access', (answer for step 4)

**Comment by bluewavenet** [comment] 2021-04-09 07:25
@bharathkspot 
Then that is the problem.
Your test router is not configured correctly ie it cannot provide Internet access when openNDS is running.

openNDS cannot magically allow clients to access the Internet if the Internet is not available to the client's lan.

**Comment by bharathkspot** [comment] 2021-04-09 07:31
> @bharathkspot
> Then that is the problem.
> Your test router is not configured correctly ie it cannot provide Internet access even when openNDS is not running.
> 
> openNDS cannot magically allow clients to access the Internet if the Internet is not available to the client's lan.

@bluewavenet 
thank you for the quick reply.
u mean to say, even though openNDS is not running i need to make sure that my router is providing intrenet to the connected cleints?. if that is the i ll check with configs of router and let u know.

**Comment by bluewavenet** [comment] 2021-04-09 07:44
@bharathkspot 

> u mean to say, even though openNDS is not running i need to make sure that my router is providing intrenet to the connected cleints?

Obviously. Like I said, openNDS cannot create Internet access where none exists.
Clearly, the router itself can access the Internet (as I can see entries in the logs and you get to see the portal pages)- but clients (in the absence of a running openNDS) cannot.

**Comment by bharathkspot** [comment] 2021-04-09 07:56
> @bharathkspot
> 
> > u mean to say, even though openNDS is not running i need to make sure that my router is providing intrenet to the connected cleints?
> 
> Obviously. Like I said, openNDS cannot create Internet access where none exists.
> Clearly, the router itself can access the Internet (as I can see entries in the logs and you get to see the portal pages)- but clients (in the absence of a running openNDS) cannot.


@bluewavenet ,

i changed my network configs to allow internet access to the connected clients irrespective of OpenNDS, the 4th step in the prev to previous message is working now(i can able to access the internet on my laptop).

but again no luck, once i start testing for OpenNDS, i mean after starting opennds and authenticating on laptop, again the inntenet is not working.

**Comment by bluewavenet** [comment] 2021-04-09 08:19
@bharathkspot 
What make and model is the router?

Please show the output of:
`cat /etc/board.json`

**Comment by bharathkspot** [comment] 2021-04-09 10:24
> @bharathkspot
> What make and model is the router?
> 
> Please show the output of:
> `cat /etc/board.json`

@bluewavenet ,

below s the output:
root@OpenAp-400270:~# cat /etc/board.
board.d/    board.json
root@OpenAp-400270:~# cat /etc/board.json 
{
	"model": {
		"id": "tp-link,ap2220",
		"name": "tp-link AP2220"
	},
	"network": {
		"lan": {
			"ifname": "eth0",
			"protocol": "static"
		}
	}
}
root@OpenAp-400270:~#

**Comment by bluewavenet** [comment] 2021-04-09 10:31
@bharathkspot 
You don't seem to have a wan configuration.
Please show the outputs of:
`uci show network`

and

`ifconfig`

**Comment by bharathkspot** [comment] 2021-04-09 10:46
@bluewavenet , 

**below is the output of uci show network:**
root@OpenAp-400270:~# uci show network
network.loopback=interface
network.loopback.ifname='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.globals=globals
network.globals.ula_prefix='fdae:4dd9:dfcf::/48'
network.wan=interface
network.wan.ifname='eth1'
network.wan.proto='dhcp'
network.lan=interface
network.lan.type='bridge'
network.lan.ifname='eth0'
network.lan.proto='static'
network.lan.ipaddr='172.168.5.1'
network.lan.netmask='255.255.255.0'
network.lan.ip6assign='60'
network.lan.vlan_filtering='1'


**output of ifconfig:**
root@OpenAp-400270:~# ifconfig 
br-lan    Link encap:Ethernet  HWaddr 20:85:93:40:02:70  
          inet addr:172.168.5.1  Bcast:172.168.5.255  Mask:255.255.255.0
          inet6 addr: fdae:4dd9:dfcf::1/60 Scope:Global
          inet6 addr: fe80::2285:93ff:fe40:270/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:28127 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17916 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3769200 (3.5 MiB)  TX bytes:7032329 (6.7 MiB)

eth0      Link encap:Ethernet  HWaddr 20:85:93:40:02:70  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:74891 errors:0 dropped:112 overruns:0 frame:0
          TX packets:56788 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:10748337 (10.2 MiB)  TX bytes:22826386 (21.7 MiB)

eth1      Link encap:Ethernet  HWaddr 20:85:93:40:02:71  
          inet addr:172.20.11.179  Bcast:172.20.11.255  Mask:255.255.255.0
          inet6 addr: fe80::2285:93ff:fe40:271/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:53339 errors:0 dropped:179 overruns:0 frame:0
          TX packets:32397 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:29080001 (27.7 MiB)  TX bytes:5761150 (5.4 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:37397 errors:0 dropped:0 overruns:0 frame:0
          TX packets:37397 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3348967 (3.1 MiB)  TX bytes:3348967 (3.1 MiB)

**Comment by bluewavenet** [comment] 2021-04-09 11:08
@bharathkspot 
Why do you have vlan_filtering set to 1? 
Try setting it to 0

**Comment by bluewavenet** [comment] 2021-04-09 13:26
@bharathkspot 
As far as I can see, the tp-link AP2220 is not officially supported by OpenWrt.

**Closed** 2021-04-11 05:42 UTC

**Comment by bharathkspot** [comment] 2021-04-15 06:20
> @bharathkspot
> Why do you have vlan_filtering set to 1?
> Try setting it to 0
hi @bluewavenet ,

fyi : even after changing the 'vlan_filtering' option to '0' also the acess to the internet for opnnds client is not there.

the 'vlan_filtering' option was forcefully often keeps getting updated to '1' by /usr/opensync/bin/nm, so i moved the nm to different location to make sure that not running in background, but still there no luck to get net access

**Comment by bharathkspot** [comment] 2021-04-15 06:31
> tp-link AP2220

@bluewavenet ,

but w.r.t the default configs of openNDS 8.1.1 as below, the internet access s allowed to client

root@OpenAp-400270:~# uci show /etc/config/opennds 
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].gatewayfqdn='status.client'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'


below are the snaps for above configs once after CPD at connected laptop.
![Screenshot from 2021-04-15 11-56-57](https://user-images.githubusercontent.com/81303982/114824263-46bea100-9de2-11eb-852f-7a8b4b3db53b.png)
![Screenshot from 2021-04-15 11-56-51](https://user-images.githubusercontent.com/81303982/114824267-47efce00-9de2-11eb-9d24-77d8af36cd63.png)
![Screenshot from 2021-04-15 11-56-45](https://user-images.githubusercontent.com/81303982/114824270-48886480-9de2-11eb-9e91-57ac31777fa7.png)


**the problem is with the below configs**

root@OpenAp-400270:~# uci show opennds
opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].use_outdated_mhd='0'
opennds.@opennds[0].webroot='/etc/opennds/htdocs'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].gatewayfqdn='status.client'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].fasport='443'
opennds.@opennds[0].fasremotefqdn='blue-wave.net'
opennds.@opennds[0].fasremoteip='46.32.240.41'
opennds.@opennds[0].faspath='/fas/fas-aes-https.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='3'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

**Comment by bluewavenet** [comment] 2021-04-15 07:44
@bharathkspot 
1. You appear to be using hardware that is either obsolete or not officially released by by the manufacturer (tp-link AP2220?)
2. The hardware you are using appears to not be supported by official OpenWrt
3. You have been less than clear about what you are trying to achieve
4. You occasionally leak snippets of some underlying complexities you have not previously mentioned
5. You are attempting to use a demo remote FAS I set up for you that is verified to be working with v8.1.1 with no special configuration requirements
6. You keep repeating the same screenshots and config details.
7. You give no explanation of what else is running on your system
8. Your responses lead me to believe that you have little or no knowledge of basic routing - I apologise if this is not the case
9. I now feel you are wasting my time trying to help you

**Comment by bharathkspot** [comment] 2021-04-15 07:57
@bluewavenet ,

it was my problem that i replied u lately, officially i was on leave for last 5 days, may be i was stuck in the middle since i was not able to disable the 'vlan_filtering' to '0', the screen shots which i have sent today are for the default configs of opennds where in which the internet access is working.

its okay, i will refer some more docs to findout the missing things, thank you very much for the help and suggestions.

**Comment by got24batman** [comment] 2021-04-16 07:48
@bluewavenet 
I am able to set up fas-aes-https.php in local web server for the https case.

Getting following error log in opennds
authmon: [ERROR: Failed_to_open_stream_to: [https://10.90.5.166:443/nds/fas-aes-https.php]]


![Screenshot (63)](https://user-images.githubusercontent.com/77356294/114990531-3972e680-9eb6-11eb-9f02-67c393e75b01.png)

**Comment by bluewavenet** [comment] 2021-04-16 09:56
@got24batman 
The TLS certificate for `https://10.90.5.166:443` is invalid. It will be self signed no doubt.
