### ISSUE TITLE
Opennds Crashing randomly.

### ISSUE THREAD

**Issue by Nxtframe** [openNDS/openNDS#378] opened 2022-08-28 08:44 UTC
Using Uhttpd now, running fas-hid.php , Server crashes when 10-11 users logins at different times or same time.
Running on a linksys E5600. Running on Opennds 9.8.0 Maybe this is a hardware limitation

My Logfiles
[opennds.txt](https://github.com/openNDS/openNDS/files/9439339/opennds.txt)
[logfile.txt](https://github.com/openNDS/openNDS/files/9439329/logfile.txt)

**Comment by bluewavenet** [comment] 2022-08-28 09:15
@Nxtframe 
Can you please show the output of `uci show opennds`
This will show all the active, uncommented, options and makes it easier to see.
Paste it in your reply text box, highlight and click the <> symbol on the top bar of the text box.

Your logs show you have numerous problems.
For example:
`Interface br-lan is at 192.168.1.1 ` This most likely clashes with the most common ip subnet used by isp routers.

`Number of Upstream gateway(s) [ 0 ]` You do not have an Internet connection, so CPD will not work (likely because of the above possible ip subnet clash).

`Token is invalid` This should rarely if ever happen and usually indicates someone is doing something weird on a client (probably because there is no Internet gateway).

`kern.info kernel: [  597.031214] ra  = 0040c01d in opennds[400000+1a000]` This is indicating a crash, but you have filtered out any other useful information that would have been in the log.

**Comment by Nxtframe** [comment] 2022-08-28 09:28
> Number of Upstream gateway(s) [ 0 ] You do not have an Internet connection, so CPD will not work (likely because of the above possible ip subnet clash).
I think this is because I took this log before pppoe with the ISP took place CPD always comes up so that is not an issue

uci show opennds
`opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].binauth='/svr/binauth_log.sh'
opennds.@opennds[0].fasport='2900'
opennds.@opennds[0].faspath='/index.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].gatewayname='Opennds'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
`

**Comment by bluewavenet** [comment] 2022-08-28 09:34
@Nxtframe 
How are you deauthenticating the client, or are they clicking logout?

I previously gave you a script function to call ndsctl.....

> CPD always comes up so that is not an issue

It will not come up on an Android or an IoS device if there is no Internet.
If you are on a computer/workstation with a standard browser, it might come up because the browser is caching the dns requests it has done recently.

PS. Please try to follow how I told you to post command outputs.....

**Comment by bluewavenet** [comment] 2022-08-28 09:44
@Nxtframe 
`opennds.@opennds[0].binauth='/svr/binauth_log.sh'`

What is `/svr`?
binauth_log.sh is in `/usr/lib/opennds/`

`opennds.@opennds[0].faspath='/index.php'`

What is `index.php`?
You said you were using fas-hid.php, so faspath will be `/fas-hid.php' `unless you have renamed it.
For uhttpd you would put fas-hid.php into `/www/`

**Comment by bluewavenet** [comment] 2022-08-28 09:47
@Nxtframe 
For some understanding of CPD, see:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

**Comment by Nxtframe** [comment] 2022-08-28 10:27
> How are you deauthenticating the client, or are they clicking logout?

Yes I'm using the status.client logout page

> It will not come up on an Android or an IoS device if there is no Internet.

There is internet it just takes a while to come up since pppoe takes a while to work. I'll replicate the error and post when internet is up.

> What is index.php?
> You said you were using fas-hid.php, so faspath will be /fas-hid.php' unless you have renamed it.
> For uhttpd you would put fas-hid.php into /www/

I created another uhttpd instance that would serve pages on /svr/www and renamed fas-hid.php to index.php and put it inside /svr/www 

( [uhttpd.txt](https://github.com/openNDS/openNDS/files/9439453/uhttpd.txt)


> I previously gave you a script function to call ndsctl.....

The Script works fine , when I tested it on my custom fas-hid.php with a simple username,password and logout previous client mac address. 
My deauth script is executed from the custom fas-hid.php
[checklocked.txt](https://github.com/openNDS/openNDS/files/9439457/checklocked.txt)

> opennds.@opennds[0].binauth='/svr/binauth_log.sh'
> 
> What is /svr?

/svr is a directory where I moved all my files and I moved binauth_log.sh to  directory /svr

Maybe I'm making it all complicated but could this be why the error is coming up

**Comment by bluewavenet** [comment] 2022-08-28 10:44
> Yes I'm using the status.client logout page

So why are you calling ndsctl?

**Comment by Nxtframe** [comment] 2022-08-28 11:27
> So why are you calling ndsctl?

Ohh this is for deauthenticating the last mac address of the user so they can only log in from one device
My deauthentication code

```
 $deauthmac = $db->query('Select clientmac from users where username="'.$username.'";') or die("Error Go Back");
 $oldmac = $deauthmac->fetchArray(SQLITE3_ASSOC);
 $oldmac_client = $oldmac['clientmac'];
			if($oldmac_client != $GLOBALS['clientmac']) {
                                 exec("/svr/checklocked.sh $oldmac_client");
                              }

```

**Comment by bluewavenet** [comment] 2022-08-28 16:39
@Nxtframe 
By the way, for some insight into CPD, see:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

**Comment by bluewavenet** [comment] 2022-08-28 16:45
@Nxtframe 
Everything looks ok from what you have shown.
We will have to see what the details of the crash reveal in the logs.....

There is a known issue on systems where free memory is running out where openNDS will silently shut down instead of reporting the problem. Your E5610 has 128MB ram so this is unlikely unless you are running lots of other things and anyway it looks like you are seeing a report of a problem with openNDS in your logs.

What does `free` show?

**Comment by Nxtframe** [comment] 2022-08-29 09:15
Here is the logfile

[log.txt](https://github.com/openNDS/openNDS/files/9443032/log.txt)

I see the error
`Sun Aug 28 14:38:53 2022 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM`

I think this might be causing firewall to restart and opennds restarting.
And further testing I see that 10-11 people connecting is not the problem even if 2-3 connects opennds restarts.

**Comment by bluewavenet** [comment] 2022-08-29 09:42
@Nxtframe 
From your logs:
`do_page_fault(): sending SIGSEGV to MHD-single for invalid read access`

This has been seen by others and it is most likely caused by a combination of issues with the new RFC8910/8908 CPI support in both openNDS and the client OS. (This should be mitigated in the upcoming openNDS release)

RFC8910/8908 CPI support is very new and should really be regarded as "experimental".
I suggest you switch it off and see if the problem is resolved.
Do the following:
```
uci set opennds.@opennds[0].dhcp_default_url_enable='0'
uci commit opennds
service opennds restart

```
The log message `daemon.info dnsmasq[1]: exiting on receipt of SIGTERM` is not an error (note it says "daemon.info"), it is an informational message. On startup, openNDS requests that dnsmasq restarts.

**Comment by bluewavenet** [comment] 2022-08-30 10:17
@Nxtframe 
Did you try disabling RFC8910/8908 CPI support?

**Comment by Nxtframe** [comment] 2022-08-30 12:53
> @Nxtframe Did you try disabling RFC8910/8908 CPI support?

I did deactivate RFC8910/8908 and connected it directly to my wan port.
Yesterday I tested it with my custom fas-hid.php(https://github.com/Nxtframe/Opennds_username_password)

And I can see that it still crashes 
```

opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].fasport='2900'
opennds.@opennds[0].faspath='/index.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].binauth='/svr/binauth_log.sh'
opennds.@opennds[0].gatewayname='Opennds'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 80' 'allow tcp port 443'
opennds.@opennds[0].dhcp_default_url_enable='0'
opennds.@opennds[0].debuglevel='3'
```

[logr.txt](https://github.com/openNDS/openNDS/files/9452848/logr.txt)

```
Tue Aug 30 16:57:25 2022 daemon.debug opennds[5916]: An authenticated client is requesting: host [status.client] url [/images/splash.jpg]
Tue Aug 30 16:57:25 2022 kern.info kernel: [ 7779.046571] do_page_fault(): sending SIGSEGV to MHD-single for invalid read access from 77dfa726
Tue Aug 30 16:57:25 2022 kern.info kernel: [ 7779.055475] epc = 77dce2fc in libc.so[77d4e000+a9000]
Tue Aug 30 16:57:25 2022 kern.info kernel: [ 7779.060555] ra  = 0040c01d in opennds[400000+1a000]
```

Might not have tested it properly I'll do so again today

**Comment by Nxtframe** [comment] 2022-08-30 12:55
I'm also running on Openwrt 22.03 rc6 could that be a problem

**Comment by bluewavenet** [comment] 2022-08-30 13:12
@Nxtframe 
`do_page_fault(): sending SIGSEGV to MHD-single for invalid read access`
This is most likely the system failing to allocate memory for the status.client request. This results in openNDS silently shutting down, which in turn results in the web server MHD pagefaulting in an outstanding service request.

What else are you running on the router?

This has been seen in systems with low free memory and the upcoming release makes openNDS report the problem rather than silently die, preventing the pagefault and serving an error503 page instead, before continuing.
I am not sure if this is the issue you have but it looks very very similar.

22.03 rc6 should not be a problem.
You could check the iptables version though.
`iptables -V`
It should be the nft version.

**Comment by Nxtframe** [comment] 2022-08-30 13:55
> This has been seen in systems with low free memory and the upcoming release makes openNDS report the problem rather than silently die

Might be this because when I tested on my virtual machine it works perfectly.

**Comment by bluewavenet** [comment] 2022-08-31 19:30
@Nxtframe 
I'll compile v9.9.0beta for your E5600 if you are willing to test it.
This new version has refactored memory management and uses significantly less memory, so hopefully this issue will be fixed.

**Comment by Nxtframe** [comment] 2022-09-01 05:09
I'm willing to test it out on my system and test it out.

**Comment by bluewavenet** [comment] 2022-09-02 06:09
@Nxtframe 
Download the beta from here:
https://github.com/openNDS/openNDS/blob/master/community/v9.9.0beta/opennds_9.9.0beta-2_mipsel_24kc-nft.ipk

**Comment by bluewavenet** [comment] 2022-09-05 20:53
@Nxtframe 

> I'm willing to test it out on my system 

It would be useful if you could do so and report the results.

**Closed** 2022-09-06 21:53 UTC
