### ISSUE TITLE
Volume Quotas - Unexpected results

### ISSUE THREAD

**Issue by sicelo** [openNDS/openNDS#57] opened 2020-09-25 07:51 UTC
I am setting up quotas based on volume for my hotspot. However, as reported by BinAuth log, it seems the actual amount of traffic passed varies in a large way.

Setting quota in custom variable:
(50kB download expected)
```
root@OpenWrt:/www/nds# tail -f /tmp/ndslog/binauthlog.log 
Fri Sep 25 09:16:43 SAST 2020, method=auth_client, clientmac=68:f7:28:a7:ec:87, clientip=192.168.1.229, username=na, password=na, redir=http://192.168.1.1/, useragent=curl/7.72.0, token=1bc10f10, custom=0 0 0 50
Fri Sep 25 09:16:43 SAST 2020, method=client_auth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=0, bytes_outgoing=0, session_start=1601018203, session_end=1601090203, token=1bc10f10
Fri Sep 25 09:18:21 SAST 2020, method=downquota_deauth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=243279, bytes_outgoing=56735, session_start=1601018203, session_end=1601018301, token=1bc10f10
```
(70kB download expected)
```
Fri Sep 25 09:21:55 SAST 2020, method=auth_client, clientmac=68:f7:28:a7:ec:87, clientip=192.168.1.229, username=na, password=na, redir=http://192.168.1.1/, useragent=curl/7.72.0, token=cfa4a702, custom=0 0 0 70
Fri Sep 25 09:21:55 SAST 2020, method=client_auth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=0, bytes_outgoing=0, session_start=1601018515, session_end=1601090515, token=cfa4a702
Fri Sep 25 09:22:21 SAST 2020, method=downquota_deauth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=448232, bytes_outgoing=36110, session_start=1601018515, session_end=1601018541, token=cfa4a702
```
(100kB download expected)
```
Fri Sep 25 09:31:27 SAST 2020, method=auth_client, clientmac=68:f7:28:a7:ec:87, clientip=192.168.1.229, username=na, password=na, redir=http://192.168.1.1/, useragent=curl/7.72.0, token=c09f3cf6, custom=0 0 0 100
Fri Sep 25 09:31:27 SAST 2020, method=client_auth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=0, bytes_outgoing=0, session_start=1601019087, session_end=1601091087, token=c09f3cf6
Fri Sep 25 09:34:21 SAST 2020, method=downquota_deauth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=449851, bytes_outgoing=52152, session_start=1601019087, session_end=1601019261, token=c09f3cf6
```
and setting it in ndsctl
```
root@OpenWrt:/www/nds# ndsctl auth 192.168.1.229 0 0 0 0 100
Client 192.168.1.229,0,0,0,0,100 authenticated.
```

resulted in:

```
Fri Sep 25 09:37:17 SAST 2020, method=ndsctl_auth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=0, bytes_outgoing=0, session_start=1601019437, session_end=0, token=095e40b4, custom=
Fri Sep 25 09:39:21 SAST 2020, method=downquota_deauth, clientmac=68:f7:28:a7:ec:87, bytes_incoming=1435399, bytes_outgoing=78023, session_start=1601019437, session_end=1601019561, token=095e40b4
```

I am a bit lost at this point.
I'm using OpenNDS 5.2.0 from OpenWrt repos.
Will appreciate any help

**Comment by bluewavenet** [comment] 2020-09-25 18:01
@sicelo 
Sorry I have not had time to look at this today, probably won't until Sunday.

This was well tested before its release at FAS level 3 but not so intensively  at levels 0,1&2

The quota will most likely always be exceeded to some extent as openNDS checks at the checkinterval, so depends on the data rate and value of checkinterval. It should never be less than the quota though.

It could be a bug ... or a regression, as I do have a vague recollection of seeing this before ... I will have to do some tests.

**Comment by bluewavenet** [comment] 2020-09-25 18:26
@sicelo 
I had a quick look anyway :-D
It might have been fixed in v6.0.0.
Try the v6.0.0 binauth_log.sh
https://github.com/openNDS/openNDS/blob/master/forward_authentication_service/binauth/binauth_log.sh

Not sure if this fixes it.

**Comment by sicelo** [comment] 2020-09-26 09:27
On Fri, Sep 25, 2020 at 11:26:39AM -0700, Rob White wrote:
> @sicelo 
> I had a quick look anyway :-D

https://xkcd.com/705/

> It might have been fixed in v6.0.0.
> Try the v6.0.0 binauth_log.sh
> https://github.com/openNDS/openNDS/blob/master/forward_authentication_service/binauth/binauth_log.sh
> 
> Not sure if this fixes it.

This is actually the one I have been using all this time.

**Comment by sicelo** [comment] 2020-09-26 11:47
But yes, looks like by reducing `checkinterval` to something less than 5, the quota situation is much better. So maybe it's not a bug. Just a config thing one has to play around with.

**Comment by bluewavenet** [comment] 2020-09-27 15:33
@sicelo 
I have a short time now (Sunday) to do a few tests.....

**Comment by bluewavenet** [comment] 2020-09-28 07:26
@sicelo 
I've been testing on v6.0.0 and it all seems ok. Yes, the accuracy of the data volume quota deauth depends on the setting of checkinterval as expected. There is always going to be an overrun depending on the data rate the client is using:
`deauth_overrun = (mean_client_data_rate * checkinterval_remainder_at_auth)`
where:
`checkinterval_remainder_at_auth =< checkinterval`

Note in your example:
`ndsctl auth 192.168.1.229 0 0 0 0 100`

This will auth client at 192.168.1.229 with the global settings for upload/download rates and volumes (ie global settings are those in the config file).

I noticed the ndsctl help example has the client identifier argument missing. The format for ndsctl auth should be:
`ndsctl auth mac|ip|token sessiontimeout(minutes) uploadrate(kb/s) downloadrate(kb/s) uploadquota(kB) downloadquota(kB) customstring` but you do have this correct in your example.

I am pretty sure you must have global settings in the config file...?
That is how it was intended to work, and does here on 6.0.0 anyway :-D

**Comment by sicelo** [comment] 2020-10-02 17:30
yes, thanks. :-)
right now i'm using `checkinterval = 1` and all seems good enough.
i guess this issue can be closed

**Closed** 2020-10-02 18:04 UTC
