### ISSUE TITLE
Lost control

### ISSUE THREAD

**Issue by Ethan-Yami** [openNDS/openNDS#154] opened 2021-05-01 12:07 UTC
Hello,
 Sorry to bother you.. I'm stuck now ,I do not know how to continue to make a progress.. I lost control of the router device.

 When I install the openNDS successfully ,the software is running by default, I can't configure it.. is there a way to connect to router that I can modify the configuration file? I need to continue access router by web Luci UI

Thanks.

**Comment by bluewavenet** [comment] 2021-05-02 14:20
@Ethan-Yami 

> I lost control of the router device

Do you mean you have bricked it, or do you mean you cannot access the Luci web UI?

> is there a way to connect to router that I can modify the configuration file?

Yes, use SSH. Note that Luci cannot be used to configure openNDS.

> I need to continue access router by web Luci UI

By default, openNDS blocks access to Luci. You need to edit the uhttpd config to move Luci from port 80 to something else eg port 81
openNDS version 9.0.0 onwards has the option of disabling the Error511/Status page, thus allowing access to port 80 and therefore the Luci UI.

**Comment by Ethan-Yami** [comment] 2021-05-05 11:31
Yes, I have bricked it. I'm testing now. Thank you!

**Comment by Ethan-Yami** [comment] 2021-05-05 13:03
Sorry to bother you again, Sir.

   Could you please help me to have a look at the configuration file which I modify it  that doesn't work. All users can access the Internet when the opennds is running. 

The configuration file is below:

config opennds
	option enabled 1
	option fwhook_enabled '1'
	option login_option_enabled '0'
	list fas_custom_parameters_list 'location=main_building admin_email=test'
	option allow_legacy_splash '1'
	option gatewayinterface 'br-lan'
	option gatewayport '2080'
	option gatewayname 'OpenWrt openNDS'
	option gatewayfqdn 'status.client'
	option maxclients '250'
	option preauthidletimeout '30'
	option authidletimeout '120'
	option sessiontimeout '1200'
	option checkinterval '60'	
	option uploadrate '0'
	option downloadrate '0'
	option ratecheckwindow '2'
	option uploadquota '0'
	option downloadquota '0'
	#option binauth '/usr/lib/opennds/binauth_log.sh'
	option fasport '80'
	option fasremotefqdn 'opennds.ethan-yang.cn'
	option fasremoteip '106.13.21.9'
	option faspath '/portal/login'	
	option faskey '1234567890'
	option fas_secure_enabled '2'
	list authenticated_users 'allow all'
	list preauthenticated_users 'allow udp port 53'
	list walledgarden_fqdn_list 'shanghai-cdn.ethan-yang.cn api-cn.ethan-yang.cn'
	list walledgarden_port_list '80 443'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 23'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'


Or could you please give me an example to make it running?

Thank you so much sir!!!

**Comment by Ethan-Yami** [comment] 2021-05-05 13:05
I have already install  these packages

1.dnsmasq-full | 2.84-1

2.ipset | 7.6-1

**Comment by bluewavenet** [comment] 2021-05-05 14:09
@Ethan-Yami 
You have a number of things wrong.
eg:
 * opennds.ethan-yang.cn is not a resolveable FQDN
 * You have legacy splash enabled
 * faspath is probably incorrect

and probably more.

Please state:
1. your hardware
2. Version of OpenWrt
3. Version of openNDS
4. are you using one of the example FAS scripts? If so, which one?

**Comment by Ethan-Yami** [comment] 2021-05-05 14:36
1. My hardware device is a router which is running openwrt, the detail information is below:
  Hostname	OpenWrt
  Model	Xiaomi Mi Router 3G
  Architecture	MediaTek MT7621 ver:1 eco:3
  Firmware Version	OpenWrt 21.02-SNAPSHOT r16055-d57e480 / LuCI openwrt-21.02 branch git-21.121.33092-0eb4e09
  Kernel Version	5.4.111
2. Version of openwrt is 	OpenWrt 21.02-SNAPSHOT 
3. Version of openNDS is opennds	8.1.1-1
4. I'm trying to use it ,but not working, I connect to the Wi-Fi network or RJ-45 cable line to the router, I can access the internet  without any authentication.
The command in openwrt via SSH are below:
root@OpenWrt:~# service opennds status
running
root@OpenWrt:~# 
---------------------------------------------
Q：opennds.ethan-yang.cn is not a resolveable FQDN
A：Just an example here. it is not a truely FQDN 
Q;You have legacy splash enabled
A: How do I modify it?
Q:faspath is probably incorrect
A: Yes, I know, Just an example.

**Comment by Ethan-Yami** [comment] 2021-05-05 14:54
option fasport '80'
option fasremotefqdn 'portal.cloudshotspot.com'
list walledgarden_fqdn_list 'shanghai.cloudshotspot.com api-cn.cloudshotspot.com'
list walledgarden_port_list '80 443'

**Comment by Ethan-Yami** [comment] 2021-05-05 15:16
option fasport '80'
option fasremotefqdn 'portal.wiwiz.com'
list walledgarden_fqdn_list 'shanghai.wiwiz.com api-cn.wiwiz.com'
list walledgarden_port_list '80 443'

**Comment by bluewavenet** [comment] 2021-05-05 16:10
@Ethan-Yami 

Are you using the fas-aes.php example script?

Can you show me the output of:
`ndsctl status`

**Comment by Ethan-Yami** [comment] 2021-05-06 00:30
ndsctl status
ndsctl: opennds probably not started (Error: No such file or directory)

**Comment by Ethan-Yami** [comment] 2021-05-06 00:30
root@OpenWrt:~# ndsctl status
ndsctl: opennds probably not started (Error: No such file or directory)
root@OpenWrt:~#

**Comment by bluewavenet** [comment] 2021-05-06 11:34
@Ethan-Yami 

> ndsctl: opennds probably not started

Run the following commands:
```
service log restart
service opennds restart
```

Wait just a second or two then run:
`logread -e "opennds"`

and show me the output...

**Comment by Ethan-Yami** [comment] 2021-05-06 14:25
BusyBox v1.33.0 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 21.02-SNAPSHOT, r16055-d57e480
 -----------------------------------------------------
root@OpenWrt:~# service log restart
root@OpenWrt:~# service opennds restart
root@OpenWrt:~# logread -e "opennds"
root@OpenWrt:~# logread -e "opennds"
root@OpenWrt:~#

**Comment by bluewavenet** [comment] 2021-05-06 15:21
@Ethan-Yami 

What are all the strike outs?

Please just show the final output of:
service log restart
service opennds restart
logread -e "opennds"

**Comment by Ethan-Yami** [comment] 2021-05-08 02:47
Sorry to bother you .

 Nothing to show,  it's just empty. There's no response after I entered these commands above.

Thank you so much sir, I will compile a new firmware and opennds.

If there's good new things , I will let you know... 


 Thank you for your supportting!

**Comment by bluewavenet** [comment] 2021-05-08 05:03
@Ethan-Yami 
If there is truly no response from the logs then it seems openNDS is not installed correctly.
Try doing:
```
mv /etc/config/opennds/opennds /etc/config/opennds/opennds.saved
opkg update
opkg install opennds --force-reinstall
```

**Comment by Ethan-Yami** [comment] 2021-05-08 13:23
root@OpenWrt:~# logread -e "opennds"
Sat May  8 13:22:07 2021 daemon.notice opennds[6712]: Handler for termination caught signal 15
Sat May  8 13:22:08 2021 daemon.notice opennds[7223]: openNDS Version 8.1.1
Sat May  8 13:22:08 2021 daemon.notice opennds[7223]: Added Custom Parameter [location=main_building]
Sat May  8 13:22:08 2021 daemon.notice opennds[7223]: Added Custom Parameter [admin_email=test]
Sat May  8 13:22:08 2021 daemon.err opennds[7223]: Bad arg 2080 to option gatewayport on line 17 in /tmp/etc/opennds_cfg01995c.conf
Sat May  8 13:22:08 2021 daemon.err opennds[7223]: Exiting...
Sat May  8 13:22:13 2021 daemon.notice opennds[7231]: openNDS Version 8.1.1
Sat May  8 13:22:13 2021 daemon.notice opennds[7231]: Added Custom Parameter [location=main_building]
Sat May  8 13:22:13 2021 daemon.notice opennds[7231]: Added Custom Parameter [admin_email=test]
Sat May  8 13:22:13 2021 daemon.err opennds[7231]: Bad arg 2080 to option gatewayport on line 17 in /tmp/etc/opennds_cfg01995c.conf
Sat May  8 13:22:13 2021 daemon.err opennds[7231]: Exiting...

**Comment by bluewavenet** [comment] 2021-05-08 13:49
@Ethan-Yami 
Congratulations, you have found a bug :-D
It seems there is a typo in the initial setup code that prevents the setting of gatewayport to anything other than the default.

Remove the line
``option gatewayport '2080' ``

and restart opennds....

**Comment by Ethan-Yami** [comment] 2021-05-08 14:27
Yes, I already remove the option gatewayport. 

I'm here happy to tell you . good things , do you remember that I asked you does the opennds support the CDN before? Now , It's working well. Perfect...


But, during the opennds re-installation, I found a lot of modules is required. such as PHP PHP_CLI PHP_open_ssh,IPSET,....

I'm really concern about the performance....


And another thing I wanna let you know. that it is the client will redirect to the FAS site at first time, if I close the browser window without authtication, Then I open browser enter(type a new website which i want to access) into a website that the page can not redirect to FAS site(Website)...


If I only type this URL "http://detectportal.firefox.com/success.txt" that will be fine...


and a little bit information maybe I will share with you after 2 or 3 days later.


Thank you so much sir.!!!

**Comment by bluewavenet** [comment] 2021-05-08 15:07
@Ethan-Yami 

> I found a lot of modules is required. such as PHP PHP_CLI PHP_open_ssh,IPSET,....

PHP_CLI  and PHP_open_ssh are required for fas levels 2 and 3 and are used for aes encryption. These were chosen over other methods as they provide high efficiency in both speed and resource requirements.

IPSET and dnsmasq-full are required for Walled Garden support.

> I'm really concern about the performance....

What concerns do you have? Do you have a performance issue?

> the client will redirect to the FAS site at first time, if I close the browser window without authtication, Then I open browser enter(type a new website which i want to access) into a website that the page can not redirect to FAS site(Website)...

This is how it is supposed to work. On connection to the openNDS managed network, the "popup" login page is triggered by the client device CPD (captive portal detection). CPD is a part of the operating system running on the client.

> I close the browser window without authtication

So you have not authenticated, therefore you do not have access to anything outside the Walled Garden.

> If I only type this URL "`http://detectportal.firefox.com/success.txt`" that will be fine...

Yes. This is one of MANY common CPD detection URLs that would normally be used by the client CPD. By closing the CPD popup without logging in, you have defeated the detection process and to go back to the login page you have to either manually enter a valid http:// url or disconnect/reconnect to trigger CPD again.

**Comment by Ethan-Yami** [comment] 2021-05-09 06:20
1 . Understood.
_PHP_CLI and PHP_open_ssh are required for fas levels 2 and 3 and are used for aes encryption. These were chosen over other methods as they provide high efficiency in both speed and resource requirements.

IPSET and dnsmasq-full are required for Walled Garden support._

2. As there are modules above are requires and php will take so much memory , so I care about the performance , wchich means how many users can be connected. for example: I deploy a router with 2cores 800Mhz CPU and 128/256 RAM(Xiaomi R3G)to a samll cafe, how many guests can be hosted. 
_What concerns do you have? Do you have a performance issue?_


3. Understood , Only issue is the https will not redirect to FAS . That's ok...
_Yes. This is one of MANY common CPD detection URLs that would normally be used by the client CPD. By closing the CPD popup without logging in, you have defeated the detection process and to go back to the login page you have to either manually enter a valid http:// url or disconnect/reconnect to trigger CPD again._

**Comment by Ethan-Yami** [comment] 2021-05-09 06:35
Sir,Sorry to bother you again ,LOL....

Now I encountered an issue that I have no idea to let the client to go throught the authentication to access Internate..

I have already removed the CDN, I run the FAS php script instead. That does not work...

1.I upload the fas-aes-https.php to the FAS server "ethan-yang.cn/nds"

2. I change the configuration file such as this:


 option enabled 1
        option fwhook_enabled '1'
        #option login_option_enabled '1'
        list fas_custom_parameters_list 'location=main_building gw_id=33e94d0cfc93db247acb576d0a075fa3560cf525'
        #option allow_legacy_splash '1'
        option gatewayinterface 'br-lan'
        #option gatewayport '2050'
        option gatewayname 'OpenWrt openNDS'
        #option gatewayfqdn 'status.client'
        option maxclients '250'
        option preauthidletimeout '30'
        option authidletimeout '120'
        option sessiontimeout '1200'
        option checkinterval '60'
        option uploadrate '0'
        option downloadrate '0'
        option ratecheckwindow '2'
        option uploadquota '0'
        option downloadquota '0'
        option binauth '/usr/lib/opennds/binauth_log.sh'
        option fasport 443
        option fasremotefqdn 'ethan-yang.cn'
        option fasremoteip '106.13.21.9'
        option faspath '/nds/fas-aes-https.php'
        option faskey '1234567890'
        option fas_secure_enabled '3'
        list authenticated_users 'allow all'
        list preauthenticated_users 'allow udp port 53'
        #list walledgarden_fqdn_list 'api-cn.ethan-yang.cn shanghai.ethan-yang.cn'
        #list walledgarden_port_list '80 443'
    
        list walledgarden_port_list '80 443'
        list users_to_router 'allow tcp port 53'
        list users_to_router 'allow udp port 53'
        list users_to_router 'allow udp port 67'
        list users_to_router 'allow tcp port 22'
        list users_to_router 'allow tcp port 23'
        list users_to_router 'allow tcp port 80'
        list users_to_router 'allow tcp port 443'



Ps: I tried to close and close "option login_option_enabled binauth" but not working.


Could you please help me to sovle this issue in your spare time?



So many thanks..

**Comment by bluewavenet** [comment] 2021-05-09 07:48
@Ethan-Yami 

> As there are modules above are requires and php will take so much memory , so I care about the performance , wchich means how many users can be connected

I have many deployments of the gl-inet mt300n-v2 (16 flash/128 ram MTK7628NN @580Mhz SoC), php-cli, php-cgi, php-openssl, lighttpd web server for router based local FAS, much custom php, numerous other packages. Some busy locations regularly have over 200 simultaneous users with no issues (other than not enough bandwidth from the ISP)
So with your Xiaomi R3G, I do not expect any problems.

> Only issue is the https will not redirect to FAS

This is by design and essential. If it was supported, all connections would have a critical certificate failure.
See the documentation FAQ:
https://opennds.readthedocs.io/en/stable/faq.html#is-https-capture-supported

**Comment by bluewavenet** [comment] 2021-05-09 08:04
@Ethan-Yami 
```
option fas_secure_enabled '3'
option fasremotefqdn 'ethan-yang.cn'
option fasremoteip '106.13.21.9'
option faspath '/nds/fas-aes-https.php'
```
This means clients will be redirected by their CPD to `https://ethan-yang.cn/nds/fas-aes-https.php`
There are two problems with this redirect url:
 * The tls certificate is invalid - it is a default for `cloudshotspot.com` but needs to be for `ethan-yang.cn`. As the certificate is invalid, **the authmon daemon will refuse to connect** AND **clients will receive a dire warning**.
 * The redirect url returns "404 Not Found" so is incorrect anyway.
 
Fix these two and you should be good to go :-D

**Comment by Ethan-Yami** [comment] 2021-05-09 08:09
I have two configuration files are below:

1 .Running FAS php script：

config opennds
        option enabled 1
        option fwhook_enabled '1'
        #option login_option_enabled '1'
        list fas_custom_parameters_list 'location=main_building gw_id=33e94d0cfc93db247acb576d0a075fa3560cf525'
        #option allow_legacy_splash '1'
        option gatewayinterface 'br-lan'
        #option gatewayport '2050'
        option gatewayname 'OpenWrt openNDS'
        #option gatewayfqdn 'status.client'
        option maxclients '250'
        option preauthidletimeout '30'
        option authidletimeout '120'
        option sessiontimeout '1200'
        option checkinterval '60'
        option uploadrate '0'
        option downloadrate '0'
        option ratecheckwindow '2'
        option uploadquota '0'
        option downloadquota '0'
        option binauth '/usr/lib/opennds/binauth_log.sh'
        option fasport 443
        option fasremotefqdn 'portal.cloudshotspot.com'
        option fasremoteip '106.13.21.9'
        option faspath '/nds/fas-aes-https.php'  #'/wifidog/test'
        option faskey '1234567890'
        option fas_secure_enabled '3'
        list authenticated_users 'allow all'
        list preauthenticated_users 'allow udp port 53'
        #list walledgarden_fqdn_list 'api-cn.cloudshotspot.com shanghai.cloudshotspot.com'
        #list walledgarden_port_list '80 443'
        list walledgarden_fqdn_list 'shanghai.cloudshotspot.com api-cn.cloudshotspot.com'
        list walledgarden_port_list '80 443'
        list users_to_router 'allow tcp port 53'
        list users_to_router 'allow udp port 53'
        list users_to_router 'allow udp port 67'
        list users_to_router 'allow tcp port 22'
        list users_to_router 'allow tcp port 23'
        list users_to_router 'allow tcp port 80'
        list users_to_router 'allow tcp port 443'


2. Running with CDN 

config opennds
        option enabled 1
        option fwhook_enabled '1'
        #option login_option_enabled '1'
        list fas_custom_parameters_list 'location=main_building gw_id=33e94d0cfc93db247acb576d0a075fa3560cf525'
        #option allow_legacy_splash '1'
        option gatewayinterface 'br-lan'
        #option gatewayport '2050'
        option gatewayname 'OpenWrt openNDS'
        #option gatewayfqdn 'status.client'
        option maxclients '250'
        option preauthidletimeout '30'
        option authidletimeout '120'
        option sessiontimeout '1200'
        option checkinterval '60'
        option uploadrate '0'
        option downloadrate '0'
        option ratecheckwindow '2'
        option uploadquota '0'
        option downloadquota '0'
        option binauth '/usr/lib/opennds/binauth_log.sh'
        option fasport 443
        option fasremotefqdn 'portal.cloudshotspot.com'
        option fasremoteip '106.13.21.9'
        option faspath '/wifidog/test'
        option faskey '1234567890'
        option fas_secure_enabled '3'
        list authenticated_users 'allow all'
        list preauthenticated_users 'allow udp port 53'
        #list walledgarden_fqdn_list 'api-cn.cloudshotspot.com shanghai.cloudshotspot.com'
        #list walledgarden_port_list '80 443'
        list walledgarden_fqdn_list 'shanghai.cloudshotspot.com api-cn.cloudshotspot.com'
        list walledgarden_port_list '80 443'
        list users_to_router 'allow tcp port 53'
        list users_to_router 'allow udp port 53'
        list users_to_router 'allow udp port 67'
        list users_to_router 'allow tcp port 22'
        list users_to_router 'allow tcp port 23'
        list users_to_router 'allow tcp port 80'
        list users_to_router 'allow tcp port 443'


Are these any error in these configuration files ?
Because they can not used to pass the authentication.

**Comment by Ethan-Yami** [comment] 2021-05-09 08:36
1. This link is generated by openNDS for running with CDN:

https://portal.cloudshotspot.com/wifidog/test?fas=OEU3bmNndlJxUVUzTWZ0VnVab0JTTC9LOGh0dWpMcFBvYVg2QlF5ZlI3Q09KUTJTTVZHOTNXWTdQTEFlcG5TSjQzN05kSmVYWmQvOWRUOTJtWVA5eUVEUDV4ZkJHazBRSDVWWStQTktMNTNsRVZ2c3FyTUZXb0xhRkx1b1FpckY3OUV3eFkvQnN0d2I4amJMbXNTdjJ2bWtxby93S0xKaEhDcGhUaS8rRkEyWldhNytrQmNlcks0TGxLeC9xZXVTbi9FdDNxb0ViWC80dXFSYXl4QkkzeXY4aE5WMW5QS1gybUp5dVZqMVlZL0F2UWZaOGgvWmVVU1V1RkFyMllDaEw4TW1Rc2xCa2VvNFpvS3RWczlZNzI2S1EzZkduUGZnK0owSm4zTW1wRDZtQ0xtWHpzbW5zUFFXRUQ5V0s3ZndRQ0hxYnV2ZjZHVG1vSHdCMllBRHk2eEdQaWR2WURnOUNOVjRpemlhc1dKVk5rT2xzbzhZaVZxZFJqbUU1cEFOS2ZXbUNmV3BZbUlyMGVDZWRyc0pNdUJ5WnNNN3FYWnIyQ3Bab1Bycmt1S1ZVem5KdVM2eEI4bXcyYkJLRnBna0w4OUxiMmZaWTdDMmxyMDk4cDNRSkF4WW9qeTVYSnRodGNlWlNwTElJb2FyOUpzSmVzNDM5clp2Y2VBb2pZTEI=&iv=16b7767497d3273a

2. This URL is generated by openNDS running with fas-aes-https.php.

https://portal.cloudshotspot.com/nds/fas-aes-https.php?fas=UVhzdWRnMDQ1eXZwN1BLZHRwTnA5VUVjRjFvaGxNT0QvdE1JNm5zM1VmcVdWdVM0SjI5ajNtZDY4NThCclVHcmhTSDNHaEZsVkhCR1RHbzVzMmpWOTlIbDZsZGRRZWJnZW8xSXFBRzVlTGRFajU0eGZmcEZ0czI5ajdBdEZ6Vkk1a3l4VHIyMVRxQy9Rd3l2dUl2S3FFaE5yZ2pIUlg3M0hvbXFFajdVbk1GbnlUZmRWZGFuSnhmMnJFbER5ZWhvd3RYVTVabHE4cmtUSENnb2RIL3oyZk9mSlNHN0pkbjNJL2thLzA0amtuWDRlQWtDeTNsWVdLR2JKS1B5K3Ircm1QRWRRNmhRNDdFK05PdUVQN09XS09rakxRaEQ0dU5zby9DUnZxRGV0MjVUcytCNy9JUkZGTVZEZGFLUThJNHU2Zy9VaVdsK1NqQ1lDeGtUVFhRQmFlQ3JhVnNvb3F6Z3F5czJQa3poUHlVOXdPcXhVYTBNcW5zeml5MFZiTG5MRE54dFJMV2tNeUNYQzZldmFTZE9CYnV2YUFmbFl2ZTk2dFpCNGIxV0RvRGIyUzVBMzUxZFdzY3RxM3Vyckp0TkpzQ01iMzhQN0dCMkZrSFQ4NVFIN0F2L0dsdVE0SHFiaFJmZ3JrZXRWRmFvbVhnUnB4YzBIWi9RcXZpeFQ4R0JSb3VrVzVVN2YrZ3VlZ2lncms5OGpZK0I0TWxGeEdqTTY4bXhzNjBZME9JPQ&iv=b11d4a11f7e1f17a


Both links can be opened . I only need to do that it's way to process the authentication.

**Comment by bluewavenet** [comment] 2021-05-09 08:47
@Ethan-Yami 
I tried from here and it looks ok - I'm using opennds v9.0.0-rc1 which has a different authmon daemon so I cannot actually log in.
What version of openNDS are you running? v8.1.1?
The authmon daemon connects to the remote FAS and the FAS communicates with openNDS. You do not have to process the authentication, authmon does it.

**Comment by Ethan-Yami** [comment] 2021-05-09 08:55
Yes, I'm runing the openNDS version V8.1.1 
_What version of openNDS are you running? v8.1.1?_


I tried to submit the data to my router device are below:
Get | Post has been tried already.
```
<form name="cloud" action="http://192.168.1.1:2050/opennds_auth" method="get">
        <input type="hidden" name="token" value="1620550126">
        <input type="hidden" name="fas" value="OEU3bmNndlJxUVUzTWZ0VnVab0JTTC9LOGh0dWpMcFBvYVg2QlF5ZlI3Q09KUTJTTVZHOTNXWTdQTEFlcG5TSjQzN05kSmVYWmQvOWRUOTJtWVA5eUVEUDV4ZkJHazBRSDVWWStQTktMNTNsRVZ2c3FyTUZXb0xhRkx1b1FpckY3OUV3eFkvQnN0d2I4amJMbXNTdjJ2bWtxby93S0xKaEhDcGhUaS8rRkEyWldhNytrQmNlcks0TGxLeC9xZXVTbi9FdDNxb0ViWC80dXFSYXl4QkkzeXY4aE5WMW5QS1gybUp5dVZqMVlZL0F2UWZaOGgvWmVVU1V1RkFyMllDaEw4TW1Rc2xCa2VvNFpvS3RWczlZNzI2S1EzZkduUGZnK0owSm4zTW1wRDZtQ0xtWHpzbW5zUFFXRUQ5V0s3ZndRQ0hxYnV2ZjZHVG1vSHdCMllBRHk2eEdQaWR2WURnOUNOVjRpemlhc1dKVk5rT2xzbzhZaVZxZFJqbUU1cEFOS2ZXbUNmV3BZbUlyMGVDZWRyc0pNdUJ5WnNNN3FYWnIyQ3Bab1Bycmt1S1ZVem5KdVM2eEI4bXcyYkJLRnBna0w4OUxiMmZaWTdDMmxyMDk4cDNRSkF4WW9qeTVYSnRodGNlWlNwTElJb2FyOUpzSmVzNDM5clp2Y2VBb2pZTEI">
        <input type="hidden" name="iv" value="16b7767497d3273a">
        <input type="hidden" name="terms" value="yes">
        <input type="hidden" name="email" value="tech@ethan-yang.cn">
        <input type="hidden" name="popup" value="false">
    </form>
```

Could you please help me to have a look at it？ What should I modify it? 
Many Thanks

**Comment by bluewavenet** [comment] 2021-05-09 08:55
@Ethan-Yami 

> This URL is generated by openNDS running with fas-aes-https.php.

Looks good, should work ok. My access should have left a log on your fas server

**Comment by Ethan-Yami** [comment] 2021-05-09 08:56
I will have a check with it.  Thanks.
_Looks good, should work ok. My access should have left a log on your fas server_

**Comment by bluewavenet** [comment] 2021-05-09 09:06
@Ethan-Yami 

> I tried to submit the data to my router device are below:
> Get | Post has been tried already.

fas_secure_enabled '3' does not use the http get method /opennds_auth/
Instead it uses authmon to tunnel inbound through your nat/firewall to access opennds directly for authentication.
So unfortunately none of your html is relevant.

**Comment by bluewavenet** [comment] 2021-05-09 09:12
@Ethan-Yami 
In v 8.1.1, the relevant part of fas-aes-https.php is lines 125 to 212. This is where FAS sends its authentication requests to openNDS.  You should NOT modify this.

**Comment by bluewavenet** [comment] 2021-05-09 09:18
@Ethan-Yami 
For each client the function authenticate_page() is called (line328). This adds the request for authentication to the authmon request database.

**Comment by Ethan-Yami** [comment] 2021-05-09 10:56
@bluewavenet 
OK, I got it.

Thanks for your supportting, I really appreciate it.

So many thanks.

**Comment by Ethan-Yami** [comment] 2021-05-10 03:39
@bluewavenet
Hello, Sir.
I read the code of the  fas-aes-https.php 

I know that How does the openNDS work for FAS authentication.

First openNDS will redirect client's request to FAS for user's verification

and If a user has been verified then the FAS server will write a log(file_put_contents) in a directory,

Finally the openNDS will send a request to read it and the client will be ready to go.


Maybe few days later , I will share the feedback.

Thanks

**Comment by Ethan-Yami** [comment] 2021-05-12 16:03
@bluewavenet  
Hello ,Sir.

 I have an idea to make openNDS better. that can we sperate the authmon "post-request" from fas-aes-https.php? which means I can add a file only read the clients data on the FAS server. We can call it as backend API. we can sperate Front end and backend .

Or can I contribute my code to openNDS , I want to implement this function, I have read about the openNDS c & php source code, I think it's not difficult.

**Comment by bluewavenet** [comment] 2021-05-12 19:06
@Ethan-Yami 
You are very welcome to submit a pull request.
fas-aes-https has been changed somewhat in v9.0.0 (just released) so you should take the new version as the basis of any work.
Separating was considered initially, but it was decided to keep it as a single php file, more for convenience as an example.

It would be worth while for you to create a new example along the lines you have described, so please go ahead. It could be in the form of a set of files to install on a FAS server for example, with a new name - something like "https-fas" perhaps.

It is interesting that you bring this up as the v9 PreAuth has been broken up in a similar way ie frontend/backend, instead of a single bash script. :-D 
As they say - "Great minds think alike" .....  ;-)

**Closed** 2021-05-13 06:44 UTC
