### ISSUE TITLE
OpenNDS Captive Portal without Internet access

### ISSUE THREAD

**Issue by CasparNuel** [openNDS/openNDS#170] opened 2021-05-29 23:31 UTC
I want to provide a CPD popup to client devices when they connect to my network.

I'm using an RPi Zero W and OpenNDS v9.0.0

I have a webserver with a login page and it's prepared to also send the right tokens to OpenNDS. Did not yet come to a testing phase as I didn't yet get CPD to work.

I know "allowing internet access" won't do much as there is no internet routing on my RPi. It's primarily the CPD pop-up I want to get to work right now.

The server is fully up and Running. It's Apache2 + php on `192.168.4.1` port `80`. It is accessible if manually browsed to.

I have the options
`fasport 80`
`faspath index.php`
In opennds.conf

OpenNDS is on `wlan0`, which is the Wi-Fi network interface.

dnsmasq is set to
`address=/#/192.168.4.1`

If I surf to any http domain on the client, my webpage shows up, so the dnsmasq works properly.

However, neither my two android devices, my windows pc, my iPad or my mac detect a Captive Portal. None of them prompt for log-in or anything. They just say something along the lines of "No Internet Access, Connected".

What am I missing here?

OpenNDS seems to be starting just fine on boot, no errors in journal nor in the bootlog.

**Comment by bluewavenet** [comment] 2021-05-30 06:38
@CasparNuel 

> I know "allowing internet access" won't do much as there is no internet routing on my RPi. It's primarily the CPD pop-up I want to get to work right now.

The client CPD **_depends_** on internet routing being configured. 

I would suggest you read the documentation at :
https://opennds.readthedocs.io

Look particularly at the section "How openNDS (NDS) works"

Note also that port 80 is reserved for the openNDS client status page. You should use something other than port 80 for your Apache server if it is running on your Pi.

> dnsmasq is set to
> `address=/#/192.168.4.1`
> 
> 

This is NOT openNDS offline mode.
Offline mode is not built in and is indeed a dnsmasq config, but not the one you are using.
You have to trick the client CPD by using a valid public ip address.
Once you have it running online, you can switch to "offline mode", but it is essential to get it working online first.
This is a problem with a Pi zero of course as you only have a single wireless interface.

The Pi zero is one of the hardware types the openNDS project uses for pre release testing so with the correct configuration you can be certain that it will work for you.

**We test with both OpenWrt and Rasbian/Debian - please state your Pi operating system and version.**

**Comment by CasparNuel** [comment] 2021-05-30 09:06
@bluewavenet , I did read the docs, I even read the "How openNDS works" part a few times. I understand the bare basics. To me it isn't clear by the docs alone that Internet routing is vital.

I tought that as long as the CPD did get another response than it expected, it would serve a Pop-up.

So, that isn't the case. What configuration is required then in order to make it work?

> You have to trick the client CPD by using a valid public ip address.

Does my Pi itself have to run on a Valid public IP address? It is not intended to ever serve full internet access, so I could just give the Pi itself a valid public IP. In normal circumstances this would be advised against but that specific network should not ever route to the internet in the first place.

So, I move Apache2 to port `8080` and I replace my Pi's IP on wlan0 with e.g. `183.59.37.1/24` . What's next? How do I configure openNDS, dnsmasq and/or iptables to trip CPD, and serve my apache webserver on socket 0.0.0.0:8080 (or 183.59.37.1:8080)?

I got this exact setup to work a few years ago with NDS, but I can't for the life of me remember what the specifics were. I also no longer have access to that device or the configuration files.

Pi zero is currently running `Raspbian GNU/Linux 10 (buster)` and openNDS v9.0.0

**Comment by bluewavenet** [comment] 2021-05-30 17:11
@CasparNuel 

> I mean, Full internet routing.

So do I. Your Pi need to be set up as a router, with nat to the wide area network. This is because a DNAT redirect is required to trigger openNDS. This was the same in NoDogSplash, nothing has changed.

Yes of course you can configure a dummy interface for WAN for a system that will never go online, but FIRST you need to satisfy the basic requirements for a captive portal.

> So, I move Apache2 to port 8080

Yes, that is good (although 8080 is traditionally reserved for proxy use).

> I replace my Pi's IP on wlan0 with e.g. 183.59.37.1/24

No, that is not what I meant. 
Add  `address=/#/123.123.123.123` to the dnsmasq config.
If a device CPD sees its CPD-detect url resolving to a private address it will assume something bad is going on and disconnect (well most recent implementations do anyway)

**Comment by CasparNuel** [comment] 2021-05-30 19:04
@bluewavenet I applied all changes stated above in practice now:

Apache2 on `8081`
OpenNDS on `wlan0`
`fasport 8081`
`faspath index.php`

Dnsmasq runs `address=/#/123.123.123.123`

Still not triggering CPD though.

As temporarily enabling Internet routing for this setup is not possible for me (No skill in routing from USB tethering, and no Wi-Fi adapter on hands), I will need to find some way on how to enable the CPD pop-up and OpenNDS without ever having actual internet.

What steps do I need to follow to get that working, or is it just simply not possible?

I tought as soon as the `address=/#/123.123.123.123` was in place, the CPD should trip, OpenNDS should catch that attempt and present the index.html from Apache2 on 8081.

What do I need to add to this configuration/change in order to make this work? Apart from actual internet, ofcourse :)

Btw: thanks for the fast and clear replies :)

**Comment by bluewavenet** [comment] 2021-05-30 20:13
@CasparNuel 

> What do I need to add to this configuration/change in order to make this work?

 * You need to add a second network interface of some kind - eg eth1.
 * Configure it as a WAN interface (wlan0 will be the LAN interface clients connect to).
 * This WAN interface eg eth1 must be a dhcp client to pick up an ip address from an upstream router
 * configure LAN for NAT routing outbound for WAN
 * Configure LAN as a DHCP server providing ip default gateway and DNS (via dnsmasq) for clients connecting to it (your Pi's wireless wlan0 network)
 * Restart openNDS
 
Then it should work.

This new second network interface could be a dummy interface. OpenWrt has a dummy interface package just for circumstances like yours. I am sure there is an equivalent in Debian....

**Comment by CasparNuel** [comment] 2021-05-30 20:27
Thank you for your fast replies! I think I get the gist of it now  -- OpenNDS only catches the attempt when it gets routed. So in order for the whole system to work, there has to be some package-to-other-interface going on.

Was hoping there was a way to make the CPD trigger just on a single interface running some configurations. I am pretty sure that I got it to work with NDS without setting up a dummy interface, and without Internet access.

I just really  can't remember how.

I'll keep the issue open a little longer incase I actually get it to work, so I can describe it here. If it doesn't happen soon or the issue is in the way feel free to close it.

**Comment by CasparNuel** [comment] 2021-05-30 20:35
Hmmm, after looking around a little more I came across this post of a while ago:

> 
> 
> @alpha77788998778999877855
> For offline working you must configure dnsmasq to return a public ip address ie NOT a private (RFC1918) address.
> eg:
> address:/#/123.123.123.123
> It does not matter what it is as long as it is not a private address. It does not matter if there is something live at that address either, as, of course, you are offline.
> 
> The reason for requiring a public ip address is simple:
> An increasing number of vendor CPD implementations implement their own DNS Rebind protection by discarding upstream RFC1918 responses to their own CPD FQDN. The result is that such CPD implementations will not trigger the splash page.

[Found here](https://github.com/openNDS/openNDS/issues/68)

Reading this, It would look like my current setup should work, but it doesn't. Still a little confused as to why the whole WAN dummy interface is a requirement.

**Comment by CasparNuel** [comment] 2021-05-30 20:53
For simplicity's sake I'll briefly explain what I actually am trying to achieve, and how I was expecting to achieve it.

Expectation: When any client connects to the AP (wlan0 on rpi0w), a CP popup is displayed with my apacheserver.


Workflow:

1. Setup apache with authentication logic and pretty HTML [Done, works fine]
2. Configuring DNSMASQ to trick the whole CPD system (`address=/#/123.123.123.123`)
3. Setting up OpenNDS to handle the request-to-actual-popup part of the situation.


The last step is where I'm currently struggling.

Do I understand your messages correctly when I say:

OpenNDS **requires** a second (dummy) interface that is the default gateway of the interface where OpenNDS is active?
OpenNDS Can't function without that second interface.

Or is there a way to make it all work on a single interface using Apache2, Dnsmasq and OpenNDS?

It's the second dummy interface part I just don't understand -- can't you trigger the CPD on the single interface using the dnsMasq trick and just serve the Apache webserver on that request? What makes it so that a second interface is required?

**Comment by bluewavenet** [comment] 2021-05-30 21:32
@CasparNuel 
I wrote the `@alpha77788998778999877855` response above - a couple of years ago I think.

openNDS, NoDogsplash, in fact any captive portal, all use a DNAT redirect to the portal on an attempted port 80 access by a client.

All client devices these days have a built in captive portal detection function (CPD) as part of their Network Manager or equivalent. On connection to a network the client CPD attempts to access a known web page on port 80. It first does a DNS request to get the ip address, then tries to connect. The captive portal firewall traps the access attempt and does a DNAT redirect (look it up under iptables), to the portal web page or pages.

We have to set the DNS reply to some valid public ip address, as otherwise the CPD will drop the connection as a man-in-the-middle attack.

The problem you have is that you are using a Rpi Zero W. This only has a single network interface ( a very bad one at that). This creates some difficulty setting up  a DNAT redirect for packets directed towards an external ip address, when there is no route defined if there is only a single interface.

**Comment by bluewavenet** [comment] 2021-05-30 21:39
@CasparNuel 
What happens if you run:
`modprobe dummy`

**Comment by bluewavenet** [comment] 2021-05-30 21:43
If it does not give an error, try:
`ip link add dummy0 type dummy'

**Comment by bluewavenet** [comment] 2021-05-30 21:44
With luck you will now have an interface dummy0

**Comment by bluewavenet** [comment] 2021-05-30 21:51
Bring the dummy interface up with:
`ip link set dummy0 up`

Then run:
`ip link`
or 
`ifconfig` to see if it worked.

**Comment by CasparNuel** [comment] 2021-05-31 12:27
@bluewavenet 
`3: dummy0 <BROADCAST, NOARP, UP, LOWER_UP> ...`

The dummy interface seems to be working. Thank you for the detailed instructions.

Sadly, still not getting the CPD served when clients connect to my AP. What are the next steps? Do I need to configure a default gateway somewhere / edit routes?


I'm a complete _noob_ when it comes to RPi networking. Only real "networking" I've ever done has all been in Cisco ios. I have no clues on how to proceed to finish my setup.

**Comment by bluewavenet** [comment] 2021-05-31 13:09
@CasparNuel 
Try following this:
https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md
You would substitute dummy0 for eth0 in this.

**Comment by CasparNuel** [comment] 2021-05-31 13:33
Okay, I now have routing enabled to dummy0, **I think**. However, CP pop-up is still not triggered on clients, and I have no skill in testing if my dummy0 interface routing is actually working properly, or faulty.

Also, with some fiddling around I noticed that the dummy0 interface does not survive reboots. How do I make sure this interface gets created on each boot?

**Comment by CasparNuel** [comment] 2021-05-31 13:49
However, manually accessing the apache webserver on `192.168.4.1:8081` is now no longer possible (error: CONNECTION_REFUSED). I assume this is the NDS firewall not allowing non-verified users to access port 8081. Which should be a good thing? Still strange that there is no CP pop-up appearing.

Or am I understanding this wrong?

**Comment by bluewavenet** [comment] 2021-05-31 14:02
You probably need:
```
fasport 8081
faspath /index.php
```

This will allow access to your apache server, assuming the initial page you want to display is at `http://192.168.4.1:8081`/index.php

**Comment by bluewavenet** [comment] 2021-05-31 14:11
You can check if the openNDS redirect is configured correctly by running:
`iptables -t nat -L ndsOUT`

This should return something like this example from my test system:
```
Chain ndsOUT (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             status.client        tcp dpt:www redir ports 2050
RETURN     all  --  anywhere             anywhere             mark match 0x20000/0x30000
RETURN     all  --  anywhere             anywhere             mark match 0x30000/0x30000
DNAT       tcp  --  anywhere             anywhere             tcp dpt:www to:10.248.1.1:2050
ACCEPT     all  --  anywhere             anywhere  
```

If you don't get the equivalent of this then your config is not correct.

**Comment by CasparNuel** [comment] 2021-05-31 14:44
Hmm, weird.

`dummy0` interface exists.
Apache FAS server is running on `192.168.4.1:8081` 
Opennds has (always been) configured to: `fasport 8081` and `faspath /index.html`

I followed the rpi route tutorial, substituting eth0 with dummy0;

I'll just put my config files here now, I'm really at a loss as to why this is not working.

`cat /etc/network/interfaces`

```
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
source-directory /etc/network/interfaces.d

iface dummy0 inet static
        address 128.128.128.128/24
        pre-up ip link add dummy0 type dummy
```

`cat /etc/opennds/opennds.conf`
```
GatewayInterface wlan0

FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
}

FirewallRuleSet users-to-router {
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 67
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}

fas_secure_enabled 0
fasport 8081
faspath /index.html
```

`cat /etc/iptables/rules.v4`
```
# Generated by xtables-save v1.8.2 on Sun May 30 03:01:17 2021
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sun May 30 03:01:17 2021
# Generated by xtables-save v1.8.2 on Sun May 30 03:01:17 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A POSTROUTING -o dummy0 -j MASQUERADE
COMMIT
# Completed on Sun May 30 03:01:17 2021
# Generated by xtables-save v1.8.2 on Sun May 30 03:01:17 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Sun May 30 03:01:17 2021
```

`cat /etc/apache2/sites-enabled/portal.conf`
```
<VirtualHost *:8081>

        ServerAdmin webmaster@localhost
        ServerName portal.local
        ServerAlias portal.local
        DocumentRoot /var/www/portal

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

The output for the command `iptables -t nat -L ndsOUT` yields
```
iptables: Operation not supported.
```

**Comment by CasparNuel** [comment] 2021-05-31 14:56
My `/etc/network/interfaces` configuration was incorrect, this has now been moved to `/etc/dhcpcd.conf`.

Still no cpd pop-up, sadly.

**Comment by CasparNuel** [comment] 2021-05-31 15:07
Dummy interface doesn't seem to created on boot. How can this be accomplished?

**Comment by bluewavenet** [comment] 2021-05-31 15:12
`iptables: Operation not supported.`

You have something fundamentally wrong. I doubt openNDS is even starting.

What does `iptables -V` give?

**Comment by bluewavenet** [comment] 2021-05-31 15:16
If you do `ndsctl status`  what do you get?

If you do:
`sudo systemctl restart opennds`
followed by:
`sudo journalctl -e`
What do you get?

**Comment by CasparNuel** [comment] 2021-05-31 15:26
`iptables -V`
```
iptables v1.8.2 (nf_tables)
```

`sudo ndsctl status`
```
ndsctl: opennds probably not started (Error: no such file or directory)
```

`sudo journalctl -e`

```
May 31 15:36:05 portal systemd[1]: Starting openNDS Captive Portal...
May 31 15:36:05 portal opennds[1766]: [5][Mon May 31 15:36:05 2021][1766](src/main.c:791) openNDS Version 9.0.0 is in startup
May 31 15:36:05 portal opennds[1766]: [5][Mon May 31 15:36:05 2021][1766](src/main.c:805) Starting as daemon, forking to background
May 31 15:36:05 portal systemd[1]: Started openNDS Captive Portal.
May 31 15:36:06 portal opennds[1766]: [3][Mon May 31 15:36:06 2021][1776](src/main.c:290) libmicrohttpd is out of date, please upgrade to version 0.9.71 or higher
May 31 15:36:06 portal opennds[1766]: [3][Mon May 31 15:36:06 2021][1776](src/main.c:293) exiting...
May 31 15:36:06 portal systemd[1]: opennds.service: Main process exited, code=exited, status=1/FAILURE
May 31 15:36:06 portal systemd[1]: opennds.service: Failed with result 'exit-code'.
May 31 15:36:06 portal systemd[1]: opennds.service: Service RestartSec=100ms expired, scheduling restart.
May 31 15:36:06 portal systemd[1]: opennds.service: Scheduled restart job, restart counter is at 1.
May 31 15:36:06 portal systemd[1]: Stopped openNDS Captive Portal.
```

**Line `libmicrohttpd is out of date, please upgrade to version 0.9.71 or higher` surprises me, I had not seen this yet. However, the libmicrohttpd I have is literally compiled as described in the docs, but instead of using a hard-coded version number when doing wget for the source tar, I just did a wget on the -latest tar. I assumed this would make sure I had the newest available version.**

P.S.: I have the source folder still on my pi, version number is `libmicrohttpd-0.9.73`, I have a newer version than the minimum version reported in the error.

Can I check wether or not a symlink/file somewhere has not been updated/ is somehow an old version of libmicrohttpd?

I have never installed libmicrohttpd on this machine before, apart from when installing openNDS, and I only used the newest sources. So it would surprise me if I somehow had an old version on this system.

**Comment by bluewavenet** [comment] 2021-05-31 15:33
Did you do this? :
```
./configure --disable-https
make
sudo rm /usr/local/lib/libmicrohttpd*
sudo make install
sudo rm /etc/ld.so.cache
sudo ldconfig -v
```

**Comment by CasparNuel** [comment] 2021-05-31 15:33
Yes, exactly as described in the documentation.

**Comment by bluewavenet** [comment] 2021-05-31 15:36
Well clearly something is wrong with it.
Download again and re compile and install....

**Comment by CasparNuel** [comment] 2021-05-31 15:41
I assume I'll have to recompile openNDS as well, after I re-compiled libmicrohttpd?

**Comment by bluewavenet** [comment] 2021-05-31 15:57
Yes. MHD (libmicrohttpd ) must be installed first.

**Comment by CasparNuel** [comment] 2021-05-31 16:05
Same error, MHD out of date. I'm using MHD 0.9.7 and openNDS 9.0.0

**Comment by CasparNuel** [comment] 2021-05-31 16:06
I followed every step of the documentation exactly. No make errors, config ran perfect with https disabled.

Not sure what I am doing wrong or what's going on here.

**Comment by bluewavenet** [comment] 2021-05-31 18:03
@CasparNuel 

> I'm using MHD 0.9.7

Is that a typo. error? The minimum version is 0.9.71.

Add to opennds.conf the following:
`debuglevel 2`

Then do:
```
service opennds restart
journalctl -e

```
opeNDS will have reported the actual version of MHD in the journal log.

I have a Pi zero W here for pre-release testing (has a usb hub with built in gigabit ethernet and a wifi dongle ).
It was running MHD 0.9.73 and openNDS 9.0.0 last month on Raspberry OS Lite. No issues at all.

_So I can confirm it does work ;-)_

Unfortunately it is currently configured with OpenWrt 21.02.0-rc1 and openNDS 9.0.1beta so I cannot easily refer to its configuration as it was then.

**Comment by CasparNuel** [comment] 2021-05-31 18:07
I understand. This is all rather confusing.

I'm currently studying for finals (Networks, actually :) ) -- I'll format my SD card and just start anew in a couple of days, see what it does. I assume somewhere somehow I have files or configs that mess it up.

I have tried everything I can think of so far - new config files, new ip addresses, recompiling, decompiling. Not yet tried that debug leven but I don't have time for it right now.

Your help is very much appreciated! I'll come back here for an update as soon as I can make the time to test it all out and get proper logs with debug information.

**Comment by CasparNuel** [comment] 2021-05-31 18:09
Last message, was a type indeed, I meant 0.9.73 :)

**Comment by bluewavenet** [comment] 2021-05-31 18:11
When openNDS compiles it includes microhttpd.h (from the untarred MHD source files). Possibly you are picking up an old version from somewhere?

**Comment by bluewavenet** [comment] 2021-05-31 18:16
If this is an academic project as part of a course, a quick way to fix the problem would be to use OpenWrt instead of RaspiOS.
The whole setup is aimed at making routing simple....

**Comment by CasparNuel** [comment] 2021-05-31 18:17
How exactly does it pick up that microhttpd.h file? Currently I have a folder `~/sources` that contains both a folder `openndsv9.0.0` and a folder `libmicrohttpd-0.9.73` containing their respective sources. When I want to compile either, I first cd into MHD, do the steps from the documentation, than step over to the nds folder, and do the steps from the documentation.

The mhd documentation contains the step `sudo rm /usr/lib/libmicrohttpd*` or something similar. I have always executed that step properly. Could it be that only removing that folder is not enough? How do I check what file is actually used in the opennds compilation process?

I can't read makefiles (yet), or at least - I only understand the very, very basics.

**Comment by CasparNuel** [comment] 2021-05-31 18:20
I have been looking into OpenWrt, as these aren't the first struggles I've been having with Raspbian and network setups. I've always opted for Raspbian because I have a debian pc - which makes the configuration and general navigation for config files etc a little easier.

I assume OpenWrt can also run mariadb and php8.0 at the same time as OpenNDS etc? It's probably a stupid question as the RPi has more than enough RAM and Power to do so but mariadb and php are requirements for my project.

And it isn't an academic project. More of a personal attempt at learning more than only the Cisco stuff.

**Comment by bluewavenet** [comment] 2021-05-31 18:24
> How exactly does it pick up that microhttpd.h file?
I can't remember but I always deleted the source folder if upgrading/downgrading etc....

**Comment by CasparNuel** [comment] 2021-05-31 18:28
I'll retry with an empty raspberry Pi somewhere in the following days/weeks and report my success (or failure) here.

If the issue persists I'll try to dive into OpenWrt and give that a shot.

**Comment by bluewavenet** [comment] 2021-05-31 18:43
> mariadb and php

Yes, both, but php 7. Apache and most other web servers as well.
Php 8 is regarded as a bit "new" for production systems on OpenWrt, particularly as it is significantly larger for not much benefit.
It will no doubt arrive in due course.

Bare in mind that although OpenWrt is real Linux, it is optimised for as small a footprint as possible with many packages split into basic with numerous extensions so it is possible to select only necessary code. It is a "headless" system, so no desktop style userland.

A typical base device might have 16MB Flash and 128MB Ram, with the low end as 8/64MB. Having said that it also runs on just about anything including server grade multi core x86-64 hardware.

**Closed** 2021-06-13 12:47 UTC

**Comment by ashah7** [comment] 2024-05-15 19:12
```
#dnsmasq file setup for captive portal will display prompt when connecting to hotspot
domain-needed
bogus-priv
address=/connectivitycheck.gstatic.com/216.58.206.131
address=/www.gstatic.com/216.58.206.99
address=/www.apple.com/2.16.21.112
address=/captive.apple.com/17.253.35.204
address=/clients3.google.com/216.58.204.46
address=/www.msftconnecttest.com/13.107.4.52
address=/connectivitycheck.platform.hicloud.com/160.44.202.175
#Below is for the future implemantation of rfc 7710
dhcp-option=160,http://hotspot.localnet/index.php
```

save as redirect.conf with above and stick it in /etc/NetworkManager/dnsmasq-shared.d


sudo nmcli general reload
sudo systemctl restart NetworkManager
sudo systemctl restart networking


bang works offline
raspi-3 
bookwork
6.6.20+rpt-rpi-v8
x64 raspian lite

**Comment by bluewavenet** [comment] 2024-05-15 19:36
@ashah7 
Sorry but this is bordering on nonsense.
Your list of canary test urls is very limited and spoofing just a few is not going to give reliable results.
Have you tried the single entry stated at the beginning of this issue?
ie.
` address=/#/123.123.123.123`

This is known to work. But the client device CPD makes use without an Internet feed fairly useless anyway.

FYI:
```
#Below is for the future implemantation of rfc 7710
dhcp-option=160,http://hotspot.localnet/index.php
```
RFC 7710 was superseded a few years ago by RFC 8910 but is still not in use by many client devices.
