### ISSUE TITLE
How to use my own verification script with openNDS?

### ISSUE THREAD

**Issue by lyt0112** [openNDS/openNDS#293] opened 2022-01-07 03:10 UTC
Hi

I am trying to make openNDS work with Redius server

I have tested radius server can work fine:
> 
 /usr/bin/radtest test 123 192.168.1.100 1218 testing123;echo $?
Sending Access-Request Id 238 from 0.0.0.0:50701 to 192.168.1.100:1812
        User-Name = 'test'
        User-Password = '123'
        NAS-IP-Address = 127.0.0.1
        NAS-Port = 1218
        Message-Authenticator = 0x00
Received Access-Accept Id 238 from 192.168.1.100:1812 to 192.168.1.26:50701 length 20
0
> 

I am trying to use binauth_custom to make it work...but ndsctl always show "Failed to authenticate"
[root@ opennds]# ndsctl auth 192.168.1.26 1400 300 1500 500000 1000000 "radtest test 192.168.1.100 1218 testing123"
Failed to authenticate client 192.168.1.26,1400,300,1500,500000,1000000,radtest test 123 192.168.1.100 1218 testing123.

How can I make it work? Any suggestion will be appreciated!!!

**Comment by bluewavenet** [comment] 2022-01-07 09:15
@lyt0112 
You will have to explain what it is you are trying to achieve as what you have revealed so far indicates you may have a few misunderstandings with respect to how it works.
Please also include details of the router hardware, router operating system + version, openNDS version.

It seems you have developed a script that uses radius to verify a set of credentials ie something like:
`/usr/bin/radtest [username] [password] [ip address of radius server] [ip port of radius server]`
and this exits with return code "0" if verification is successful.
So far so good.

I suspect the title of this issue should probably be "How to use my own verification script with openNDS"?

The command `ndsctl auth [client] [quota parameters] [custom string]' is a request to openNDS to grant the client Internet access. The "custom string" is an undefined string to be passed to a Binauth script you have enabled, it is not used for credential verification. That verification will be done in the FAS (note FAS includes ThemeSpec scripts).

**Comment by lyt0112** [comment] 2022-01-07 10:09
@bluewavenet 
I've changed the title.

My router is a PC with many NICs and installed an old OS : Fedora 21
[root@ opennds]# opennds -v
This is openNDS version 9.5.0

At first,I have modified theme_user-email-login-basic.sh to theme_user-pwd-login-basic.sh (only modified email to password)

config /etc/opennds/opennds.conf:
GatewayInterface eth3_4
login_option_enabled 3
debuglevel 3
themespec_path /usr/lib/opennds/theme_user-pwd-login-basic.sh
binauth /usr/lib/opennds/binauth_log.sh
FirewallRuleSet authenticated-users {
  FirewallRule allow all
}

FirewallRuleSet preauthenticated-users {
}
FirewallRuleSet users-to-router {
    FirewallRule allow udp port 53
    FirewallRule allow tcp port 53
    FirewallRule allow udp port 67
 \# You may want to allow ssh, http, and https to the router
 \# for administration from the GatewayInterface.  If not,
\ # comment these out.
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}

I can see captive portal and what I typed (username/password )on the /tmp/ndslog/binauthlog.log

My problem is  : 
I already have a redius server which contains username/password database. 
Old captive portal's function is simple and limited. (It is not open source project and written by other engineer more than 10 years ago) and I want to change it to openNDS.
On old captive portal use radtest command to vertify the username/password ...
So I want to use binauth to do radtest command.

**The "custom string" is an undefined string to be passed to a Binauth script you have enabled, it is not used for credential verification.**
=>I think I know what is the " misunderstandings "... What I thought was [ custom string ] of ndsctl executed by openNDS should be radtest command...but I can not make it work. Because I thought "Binauth" was used pass captive portal's auth to binary.

**That verification will be done in the FAS (note FAS includes ThemeSpec scripts).** 
=>You mean I need to add the radtest command on /usr/lib/opennds/theme_user-pwd-login-basic.sh ?
radtest return 0 means no problem , return 1 means error. 
OpenNDS theme 's default behavior is allow internet access after landing page , so I need to block internet access if radtest return 1.  All need to write into "landing_page()" ?

**Comment by bluewavenet** [comment] 2022-01-07 11:04
@lyt0112 
Perhaps a definition of BinAuth will help:
 * **Bin**ary run by openNDS when it grants Internet access to the client, during the process known as "**Auth**entication".
Normally used for local logging when the FAS is remotely located.

When using a local FAS, such as ThemeSpec, binauth_log.sh is not required. The access log is usually in the same place you found the binauth log and is named ndslog.log

>  All [I] need to [do is] write into "landing_page()" ?

Yes. Before the call to auth_log(), add a command to run your radtest script.
If it returns "0" then do the call to auth_log() and continue, else set ndsstatus to "fail", _skip_ auth_log() and continue

**Comment by lyt0112** [comment] 2022-01-10 05:22
@bluewavenet 
Hi 
The radius can work fine and thanks for your help.

I have other question:
If I use IE11 to access http://www.slime.com.tw , the browser redirect the web page to openNDS's captive portal 
After I typed the correct username/password , it show me http://www.slime.com.tw web page
But if I use Chrome to access http://www.slime.com.tw , the browser redirect the web page to openNDS's captive portal 
After I typed the correct username/password , it show me 

> IP address: 192.168.1.26
>MAC address: b8:88:e3:76:e3:ee
>Client Type: cpi_url
>Interfaces being used by this client: eth3_4
>Session Start: Mon Jan 10 11:42:12 CST 2022
>Session End: Tue Jan 11 07:42:12 CST 2022
>Last Active: Mon Jan 10 11:44:13 CST 2022
>Upload Rate Limit: Unlimited Kb/s
>Download Rate Limit: Unlimited Kb/s
>Upload Quota: Unlimited KBytes
>Download Quota: Unlimited KBytes
>Uploaded This Session: 111 KBytes
>Downloaded This Session: 215 KBytes
>Average Upload Rate This Session: 7.38 Kb/s
>Average Download Rate This Session: 14.24 Kb/s

Is it possible to make the Chrome's behavior same as IE11 ( No need to type url again. )? 
Only http can show captive portal now , how to make https also can work?

**Comment by bluewavenet** [comment] 2022-01-10 10:46
@lyt0112 
To understand this better I suggest reading:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

Almost all modern operating systems and browsers support CPD, and it looks like support for CPI is now available in the version of Chrome you are using.

It looks like the "end of life" IE11 you have tried is too old to support CPD, or perhaps it is disabled in that browser and also disabled in that old version of Windows. This means you have to manually access a port 80 web site to get the portal login page.

Note also that modern implementations of CPD will automatically close the portal "landing page". This is done for security reasons (helps prevent MITM attacks). You are getting the url you manually typed in, because the IE11 browser is outdated and insecure. 

> Only http can show captive portal now , how to make https also can work?

From the documentation link I gave:
"It is important to remember that CPD is designed primarily for mobile devices to automatically detect the presence of a portal and to trigger the login page, without having to resort to breaking SSL/TLS security by requiring the portal to redirect port 443"

The https protocol has two main functions:

1. Encrypt all traffic
2. Ensure the web site requested is the one that is received by the browser and not some MITM redirect.

**Comment by lyt0112** [comment] 2022-01-11 08:06
@bluewavenet 

My Win10's default browser is Microsoft Edge
I can see OS opened the captive portal automatically when I plugined the network cable,
I think it is the CPD. 
After authenticated successfully , the edge opened the web page: http://www.msftconnecttest.com/connecttest.txt automatically.
If I changed to Chrome to be default browser , the chrome opened the web page : https://www.msn.com/ automatically
Is it possible to specify a web page URL to replace it?

I am implementing the QoS for each authenticated user. 
I've installed sch_cake.ko and update iproute2 to support SQM.
I also checked your document , but I can't find out how to use on my linux.
Could u give me any hints?

**Comment by bluewavenet** [comment] 2022-01-11 21:03
@lyt0112 

>  Is it possible to specify a web page URL to replace it?

Technically it is possible but the built in CPD in most mobile devices and operating systems such as Linux and Windows 10 will automatically close the CPD browser or browser tab as soon as the Internet connection is detected, usually after a second or two, so setting a url to finally redirect to, is mostly useless.
The next release of openNDS will not even give the landing page button to go to the "original requested page". It is usually a blank page or a page with simple text phrase.

> I also checked your document , but I can't find out how to use [SQM scripts] on my linux.
> Could u give me any hints?

Yes, look here:
https://github.com/tohojo/sqm-scripts

**Comment by lyt0112** [comment] 2022-01-13 08:20
> Technically it is possible but the built in CPD in most mobile devices and operating systems such as Linux and Windows 10 will automatically close the CPD browser or browser tab as soon as the Internet connection is detected, usually after a second or two, so setting a url to finally redirect to, is mostly useless.
> The next release of openNDS will not even give the landing page button to go to the "original requested page". It is usually a blank page or a page with simple text phrase.

==>understand and thanks for your explain

> Yes, look here:
> https://github.com/tohojo/sqm-scripts
==> I can not find any document about how to use it from the URL...
Seems like need to read the shell code and test the behavior.
I will try and test it...

**Comment by bluewavenet** [comment] 2022-01-13 08:58
@lyt0112 
Documentation for installations other than on OpenWrt does seem to be quite sparse.
The README.md file describes how to install and do basic configuration:
https://github.com/tohojo/sqm-scripts#readme

This gives some good general information and numerous links:
https://openwrt.org/docs/guide-user/network/traffic-shaping/sqm-details

**Comment by lyt0112** [comment] 2022-01-14 05:42
@bluewavenet 
sqm is not easy to understand 
If I use the following command into the shell script...
Should I need to study the sqm project?
    Example: ndsctl auth 10.13.1.138 1400 300 1500 500000 1000000 "This is a Custom String"

**Comment by bluewavenet** [comment] 2022-01-14 07:47
@lyt0112 
Ah! I think you are misunderstanding the difference between Quotas and traffic shaping.
See:
https://opennds.readthedocs.io/en/stable/traffic.html#data-quotas-and-traffic-shaping

openNDS has built in data quotas and rate quotas. These are set either globally in the config or set for individual clients (like in your ndsctl example).

The rate quotas (thresholds) are different to and independent to the traffic shaping that SQM can do. They represent a threshold above which a client's traffic rate will become limited.

This is done without any further dependencies - ie without installing any additional packages. It works by calculating the average client rates over a time window and if the "rate quota" is exceeded, packet limiting with a bucket filter is enabled for the client until the average rate again drops below the set threshold.

Clients have an initial unrestricted interval where they can burst at maximum rate. The net result enforces a fair usage policy onto clients while enabling a good user experience in the most common situation of a public venue.

Visitors to the venue (eg a coffee shop type of environment), will typically want to download and sync locally their emails, quickly search the Internet for information, check social media channels, upload photos etc etc. Traffic in these cases is very bursty and not continuous as would be the case if Torrenting or HD video streaming for example. 

In summary:
 * openNDS data volumes deauthenticate clients that exceed their volume quota
 * openNDS rate quotas set a threshold above which the client data rate becomes limited.
 * openNDS can enforce fair usage with its built in quota management, whilst maintaining a good user experience.
 * SQM can be used to set a rate ceiling which will not be exceeded (but requires the SQM package).
 * SQM will prevent feed congestion and minimise buffer bloat
 
From this you can see, depending on the venue requirements, a combination of both openNDS rate limiting and SQM could give good results. But SQM is an independent add on that is very often not required.
 
In addition, the majority of installations of openNDS are expected to be on dedicated router grade hardware where limited flash memory and RAM is common and the addition of more packages can in some cases be problematic.

**Comment by lyt0112** [comment] 2022-01-14 09:23
@bluewavenet 

I tried to achieve the openNDS' rate limit function on SQM , but I found it is very hard.
I understand now...a lot of misunderstanding~

The following test result caused my misunderstanding:
IP address: 192.168.1.26
MAC address: b8:88:e3:76:e3:ee
Client Type: cpi_url
Interfaces being used by this client: eth3_4
Session Start: Fri Jan 14 16:22:38 CST 2022
Session End: Sat Jan 15 12:22:38 CST 2022
Last Active: Fri Jan 14 16:23:31 CST 2022
Upload Rate Limit: 300 Kb/s
Download Rate Limit: 300 Kb/s
Upload Quota: 10240 KBytes
Download Quota: 10240 KBytes
Uploaded This Session: 211 KBytes
Downloaded This Session: 5929 KBytes
Average Upload Rate This Session: 31.85 Kb/s
Average Download Rate This Session: 895.01 Kb/s

If the Quota exceed the max value , captive portal will ask me to authenticate again..it can work fine.
But Average Download Rate is 895 kb/s , my Rate limit is 300 Kb/s..it is a problem.
How to fix the problem?

**Comment by lyt0112** [comment] 2022-01-17 07:24
@bluewavenet 

IP address: 192.168.1.26
MAC address: b8:88:e3:76:e3:ee
Client Type: cpd_can
Interfaces being used by this client: eth3_4
Session Start: Mon Jan 17 14:05:29 CST 2022
Session End: Tue Jan 18 10:05:29 CST 2022
Last Active: Mon Jan 17 15:16:49 CST 2022
Upload Rate Limit: 300 Kb/s
Download Rate Limit: 300 Kb/s
Upload Quota: Unlimited KBytes
Download Quota: Unlimited KBytes
Uploaded This Session: 26048 KBytes
Downloaded This Session: 1541005 KBytes
Average Upload Rate This Session: 48.69 Kb/s
Average Download Rate This Session: 2880.38 Kb/s

I downloaded files from FTP server or Google continuously...
I tested it more than one hour , but the average speed is still very high.
How to adjust the parameters?
 I only add new parameter "ratecheckwindow 3" on the /etc/opennds.conf

**Comment by bluewavenet** [comment] 2022-01-17 08:50
@lyt0112 
As I said earlier:

> The configured "[ ] Rate Limit" is the threshold at which rate limiting is enabled for the client.

openNDS _**does not**_ set an upper ceiling to data rates.

It sets _**a threshold above which rate limiting is enabled**_ for a client.

It is designed to enforce fair usage by throttling clients that _**exceed**_ the rate threshold at a typical public captive portal venue without the requirement for installing additional packages.

Continuously downloading files over a sustained period is not typical for a public venue.
Note  my previous comment again:
> Each client has an unlimited burst interval equal to checkinterval times ratecheckwindow in seconds.

Note also:
"Average [  ] Rate This Session" is the rate at which a client has transferred data **_since logging in_**.

In your example, setting `ratecheckwindow` to 3 will allow longer unrestricted bursting by the client, thus increasing the "session average".

You can try setting `ratecheckwindow` to 1 and `checkinterval` 10 seconds to achieve a lower "session average".
However to _**set an upper ceiling for a client**_ you must install a third party traffic shaping package (eg SQM scripts).

The next release of openNDS has additional parameters for tuning rate quotas, has a more sophisticated algorithm and uses a more descriptive terminology. But additional package[s] will still be required to set an upper ceiling.

**Comment by lyt0112** [comment] 2022-01-17 09:30
@bluewavenet 
I understand now...thanks for the explain

**Comment by lyt0112** [comment] 2022-01-18 07:56
@bluewavenet 
I am studying the TC commands , and I want to add tc command on the shell scripts...
If I defined quota max=100MB and user's transfer data reached 100MB...
I want to limit the max bandwidth =500kb/s and no need to login again.
Is it possible? which hook point should I add the code?

**Comment by bluewavenet** [comment] 2022-01-18 08:25
@lyt0112 
First, develop a script that uses TC commands to hard limit a given client.
Test that this works if run manually.
BinAuth is the provided "hook point" for adding functionality to a client login.
Modify the standard binauth example script (binauth_log.sh) to call your TC script.

**Comment by lyt0112** [comment] 2022-01-27 10:03
@bluewavenet 
My TC commands can do hard limit speed to clients now.
But about the quota, how can I config different quota to different accounts?

**Comment by bluewavenet** [comment] 2022-01-27 10:57
@lyt0112 
See my previous comment:

> BinAuth is the provided "hook point" for adding functionality to a client login.
> Modify the standard binauth example script (binauth_log.sh) to call your TC script.

**Comment by lyt0112** [comment] 2022-01-28 02:45
@bluewavenet
Sorry...I mean data volume quota..
I want to limit A client can use 1GB, B client can use 2 GB on one day.
TC script doesn't support quota and only can limit the speed.

**Comment by bluewavenet** [comment] 2022-01-28 08:37
@lyt0112 

>  I want to limit - client A can use 1GB, client B can use 2 GB on one day.

Two things required:
 1. You will need to enable volume limiting **for the client** in your ThemeSpec script. openNDS will then deauth the client when the volume is exceeded.
 2. You will need to add to **your binauth script**, a check for previous volume limit deauth in the binauth log. Binauth can then disallow a second auth if the client attempts to log in before a day (or whatever period you require) has passed.

Quite simple to do.

**Comment by lyt0112** [comment] 2022-01-28 09:18
@bluewavenet 
If I have client A can use 1GB & client B can use 2GB & client C can use 0.5GB
The method you provide is enable volume limiting for every clients max=0.5GB
client A deauth 1 time and auth 1 time
client B deauth 3 times and auth 3 times
Is it correct?
Is it possible to deauth 1 time only for every client if it reach the max volume limit?

**Comment by bluewavenet** [comment] 2022-01-28 12:42
@lyt0112 

>  The method you provide is enable volume limiting for every clients max=0.5GB

No!
You want to set the volume limit **per client**.
This is done in the Themespec script when the client logs in.

Assuming your ThemeSpec is based on the theme_user-email-login-basic script, then in function `landing_page()`, before the call to `auth_log()`, add the lines:
```
upload_rate="0"
download_rate="0"
upload_quota="X"
download_quota="Y"

quotas="$session_length $upload_rate $download_rate $upload_quota $download_quota"
```
where you replace X and Y with the values, in kilobytes, required for the client in question (obtained from your radius call?).

**Comment by lyt0112** [comment] 2022-02-07 08:20
> @lyt0112
> 
> > The method you provide is enable volume limiting for every clients max=0.5GB
> 
> No! You want to set the volume limit **per client**. This is done in the Themespec script when the client logs in.
> 
> Assuming your ThemeSpec is based on the theme_user-email-login-basic script, then in function `landing_page()`, before the call to `auth_log()`, add the lines:
> 
> ```
> upload_rate="0"
> download_rate="0"
> upload_quota="X"
> download_quota="Y"
> 
> quotas="$session_length $upload_rate $download_rate $upload_quota $download_quota"
> ```
> 
> where you replace X and Y with the values, in kilobytes, required for the client in question (obtained from your radius call?).

Just come back from a vacation...understand now...thanks for the explain~

I have other question now...
If my router has two interfaces named wlan0(192.168.1.0/24) & wlan1(192.168.2.0/24)
Is it possible to make openNDS show different captive portals for wlan0 & wlan1 ?

**Comment by bluewavenet** [comment] 2022-02-07 08:45
@lyt0112 

>  Is it possible to make openNDS show different captive portals for wlan0 & wlan1 ?

Yes, but **both interfaces must be bridged on the same ip subnet.**
FAS is informed which interface the client is using and can then decide which a portal pages to serve depending on the interface used.

**Comment by lyt0112** [comment] 2022-02-07 09:09
> @lyt0112
> 
> > Is it possible to make openNDS show different captive portals for wlan0 & wlan1 ?
> 
> Yes, but **both interfaces must be bridged on the same ip subnet.** FAS is informed which interface the client is using and can then decide which a portal pages to serve depending on the interface used.

Bridge wlan0 & wlan1 to br_lan and then config 192.168.1.0/24 and 192.168.2.0/24 on the interface br_lan ?

**Comment by lyt0112** [comment] 2022-02-08 01:30
@bluewavenet 
if wlan0 & wlan1 bridged to br_lan, and clientif know the traffic sent from which original interface...why can not bind 192.168.1.1/24 and 192.168.2.1/24 on the br_lan interface?

**Comment by bluewavenet** [comment] 2022-02-08 08:34
@lyt0112 

> why can not bind 192.168.1.1/24 and 192.168.2.1/24 on the br_lan interface?

Because you cannot have two subnets on the same interface - that is a consequence of how ip works....

> "Staff" "Guests" "Office machines" must in the same subnet?

If you want a single instance of openNDS to control them, then yes.

> openNDS can be FAS server right? 

Wrong, openNDS can work **with** a FAS server located anywhere accessible. The basic ThemeSpec modes happen to use the openNDS built in web server as it is there and saves having some other web server installed on the router.

> all can be on the same Linux PC and use 127.0.0.1 to forward traffic to other different ports?

I don't understand what you mean by this.

openNDS does not support multiple instances of itself on a single machine. This could be done, but as it is a fundamental firewall limitation it would be quite time consuming to write the code.

For your scenario with user groups of Staff, Office and Guests, the most common ways of doing this are:

1. Put all groups on the same subnet, with an SSID for each. Guests being open, Staff and Office having their own passcodes. 
2. Use a low cost (~20$) router for each group. Such routers are generally very robust as designed commonly as "Travel Routers" and can handle hundreds of concurrent users in such an environment.

In your case with an old server/desktop machine, you could simulate method 2 above by running a virtual machine for each group.
This is fine for an academic exercise, but I would suggest that it is very over complicated and a single point of failure. It is not suitable for a production system in the real world.

**Comment by bluewavenet** [comment] 2022-02-08 09:35
@lyt0112 
This has gone considerably off topic so I will close this issue.
If you wish to further discuss your requirement for supporting multiple user groups, please open a new issue. :-)

**Closed by bluewavenet** 2022-02-08 09:35 UTC

**Comment by lyt0112** [comment] 2022-02-08 09:53
@bluewavenet 
`
Because you cannot have two subnets on the same interface - that is a consequence of how ip works....
`
My Linux configured many ip/subnet on a single interface. Traffic can be routed without any problem.
[root@ ~ ]# ip addr add 192.168.2.1/24 dev eth2
[root@ ~ ]# ip addr add 192.168.3.1/24 dev eth2
[root@ ~ ]# ip route|grep eth2
192.168.2.0/24 dev eth2  proto kernel  scope link  src 192.168.2.1
192.168.3.0/24 dev eth2  proto kernel  scope link  src 192.168.3.1
[root@ ~ ]# ip addr show dev eth2
7: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 00:60:e0:6a:2b:7e brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet 192.168.3.1/24 scope global eth2
       valid_lft forever preferred_lft forever
`
Wrong, openNDS can work with a FAS server located anywhere accessible. The basic ThemeSpec modes happen to use the openNDS built in web server as it is there and saves having some other web server installed on the router.
`
Understand
`
I don't understand what you mean by this.
`
Single PC can config many web server with different port. I tested and can work very well.
If I want to access web 1 with port 1234 , I use http://127.0.0.1:1234 to access the web
If I want to access web 2 with port 2345 , I use http://127.0.0.1:2345 to access the web

I understand most common ways...I will try to use single machine...if can not work , I will try to use the common ways.
`
This has gone considerably off topic so I will close this issue.
If you wish to further discuss your requirement for supporting multiple user groups, please open a new issue. :-)
`
OK...thanks for the help

**Comment by bluewavenet** [comment] 2022-02-08 11:44
@lyt0112 

> My Linux configured many ip/subnet on a single interface

You can add multiple ip addresses to an interface, but that is multi homing and not compatible with ipv4 routing. For routing, a default gateway for the subnet must be defined and used by devices on the subnet for traffic destined outside the subnet.
In your case, DHCP will not work. How will your DHCP server know which subnet to allocate an address for? It cannot. NAT will not work either. For routing in your case, you would have to define a vlan for each subnet that is sharing a physical interface, then connect client devices via a managed switch to separate out the subnets.

> If I want to access web 1 with port 1234 , I use http://127.0.0.1:1234/ to access the web
> If I want to access web 2 with port 2345 , I use http://127.0.0.1:2345/ to access the web

127.0.0.1 (or localhost) is only accessible on the **local host**, so cannot be accessed from the network.
